JAUT: jaut::EventHandler< HandlerArgs > Class Template Reference
jaut::EventHandler< HandlerArgs > Class Template Reference
The EventHandler class stores a callback to a function and makes it invocable and storable in an Event object.
#include <jaut_Event.h>
Public Types
template<class Owner >
using MemberFunction_t = MemberFunctionPointer_t< Owner, void, HandlerArgs... >
The callback type of member functions.
using FreeFunction_t = FunctionPointer_t< void, HandlerArgs... >
The callback type of free functions.
using LambdaFunction_t = FreeFunction_t
The callback type of lambda functions.
using Functor_t = FreeFunction_t
The callback type of functors.
using EventArgs_t = TypeArray< HandlerArgs... >
A type array containing the event arguments.
Public Member Functions
template<class Fn , std::enable_if_t< isHandlerFreeFunction_v< Fn, EventHandler > > * = nullptr>
EventHandler (Fn &&function)
Constructs a new EventHandler from a free function.
template<class T , std::enable_if_t< isHandlerLambdaOrFunctor_v< T, EventHandler > > * = nullptr>
EventHandler (T &&invocable)
Constructs a new EventHandler from any invocable that is not a non-static member and not a free function.
template<class CriticalSection >
EventHandler (Event< EventHandler< HandlerArgs... >, CriticalSection > &chainedEvent)
Constructs a new EventHandler from another Event, allowing to chain events.
template<class Owner >
EventHandler (MemberFunction_t< Owner > memberFunction, Owner &memberObject)
Constructs a new EventHandler from a member function.
template<class T >
EventHandler (juce::String id, T &&invocable)
Constructs a new EventHandler from any invocable with an id.
template<class Owner >
EventHandler (juce::String id, MemberFunction_t< Owner > memberFunction, Owner &memberObject)
Constructs a new EventHandler from a member function with an id.
EventHandler (const EventHandler &other) noexcept
EventHandler (EventHandler &&other) noexcept
EventHandler & operator= (EventHandler right) noexcept
template<class ... Args>
void operator() (Args &&...args) const
Calls the stored callback.
JAUT_NODISCARD bool operator== (const EventHandler &handler) const noexcept
Compares two EventHandler and returns whether their callbacks are equal, or, in associative mode, their ids.
JAUT_NODISCARD bool operator!= (const EventHandler &handler) const noexcept
Compares two EventHandler and returns whether their callbacks are not equal.
JAUT_NODISCARD bool isMemberFunction () const noexcept
Determines whether the function this handler is pointing to is a member function.
JAUT_NODISCARD bool isFreeFunction () const noexcept
Determines whether the function this handler is pointing to is a free function.
JAUT_NODISCARD bool isClosureOrFunctor () const noexcept
Determines whether the function this handler is pointing to is a functor or closure.
JAUT_NODISCARD bool isChained () const noexcept
Determines whether this handler is a chained handler, that binds another event to this one.
JAUT_NODISCARD bool isAssociative () const noexcept
Determines whether this handler is an associative handler or not.
JAUT_NODISCARD juce::String getId () const noexcept
Gets the id of the handler if it is associative, otherwise an empty string.
Detailed Description
template<class ... HandlerArgs>
class jaut::EventHandler< HandlerArgs >
The EventHandler class stores a callback to a function and makes it invocable and storable in an Event object.
An EventHandler can have 4 different types of callable, member functions, free functions, lambdas and functors.
Since member functions are handled differently than free functions, this will keep a pointer to the member function internally and also the class object to which it belongs. This makes sure that different classes with the same function pointer don't equal to functions of other classes.
Due to how lambdas work, you can not unsubscribe from them once subscribed because there is no way to check for equality. However, EventHandler allows to name such handlers, which can then be unsubscribed from through their id.
Template Parameters
HandlerArgs The arguments of the registrable callback
Member Typedef Documentation
MemberFunction_t
template<class ... HandlerArgs> template<class Owner > using jaut::EventHandler< HandlerArgs >::MemberFunction_t = MemberFunctionPointer_t<Owner, void, HandlerArgs...>
The callback type of member functions.
Template Parameters
Owner The owning class of the member function
FreeFunction_t
template<class ... HandlerArgs> using jaut::EventHandler< HandlerArgs >::FreeFunction_t = FunctionPointer_t<void, HandlerArgs...>
The callback type of free functions.
LambdaFunction_t
template<class ... HandlerArgs> using jaut::EventHandler< HandlerArgs >::LambdaFunction_t = FreeFunction_t
The callback type of lambda functions.
Functor_t
template<class ... HandlerArgs> using jaut::EventHandler< HandlerArgs >::Functor_t = FreeFunction_t
The callback type of functors.
EventArgs_t
template<class ... HandlerArgs> using jaut::EventHandler< HandlerArgs >::EventArgs_t = TypeArray<HandlerArgs...>
A type array containing the event arguments.
Constructor & Destructor Documentation
EventHandler() [1/8]
template<class ... HandlerArgs> template<class Fn , std::enable_if_t< isHandlerFreeFunction_v< Fn, EventHandler< HandlerArgs... > > > * > jaut::EventHandler< HandlerArgs >::EventHandler (Fn && function) explicit
Constructs a new EventHandler from a free function.
If the callback is a lambda, it will not be associative when constructed with this constructor.
Template Parameters
Fn The function type
Parameters
callback The function or lambda
EventHandler() [2/8]
template<class ... HandlerArgs> template<class T , std::enable_if_t< isHandlerLambdaOrFunctor_v< T, EventHandler< HandlerArgs... > > > * > jaut::EventHandler< HandlerArgs >::EventHandler (T && invocable) explicit
Constructs a new EventHandler from any invocable that is not a non-static member and not a free function.
Template Parameters
T
Parameters
invocable
EventHandler() [3/8]
template<class ... HandlerArgs> template<class CriticalSection > jaut::EventHandler< HandlerArgs >::EventHandler (Event< EventHandler< HandlerArgs... >, CriticalSection > & chainedEvent) explicit
Constructs a new EventHandler from another Event, allowing to chain events.
Be aware that this could be dangerous if the chained event is destroyed before this one, since it only points to the chained event. So make sure to remove it again before it gets destroyed.
Parameters
chainedEvent The event that refers to this handler
References jaut::operator!=(), and jaut::operator==().
EventHandler() [4/8]
template<class ... HandlerArgs> template<class Owner > jaut::EventHandler< HandlerArgs >::EventHandler (MemberFunction_t< Owner > memberFunction, Owner & memberObject)
Constructs a new EventHandler from a member function.
Template Parameters
Owner The type containing the function
Parameters
callback The member function
owner An instance of the type holding the member function
EventHandler() [5/8]
template<class ... HandlerArgs> template<class T > jaut::EventHandler< HandlerArgs >::EventHandler (juce::String id, T && invocable)
Constructs a new EventHandler from any invocable with an id.
Template Parameters
Fn The function type
Parameters
id The id of the handler
callback The function or lambda
EventHandler() [6/8]
template<class ... HandlerArgs> template<class Owner > jaut::EventHandler< HandlerArgs >::EventHandler (juce::String id, MemberFunction_t< Owner > memberFunction, Owner & memberObject)
Constructs a new EventHandler from a member function with an id.
Template Parameters
Owner The type containing the function
Parameters
id The id of the handler
callback The member function
owner An instance of the type holding the member function
EventHandler() [7/8]
template<class ... HandlerArgs> jaut::EventHandler< HandlerArgs >::EventHandler (const EventHandler< HandlerArgs > & other) noexcept
EventHandler() [8/8]
template<class ... HandlerArgs> jaut::EventHandler< HandlerArgs >::EventHandler (EventHandler< HandlerArgs > && other) noexcept
Member Function Documentation
operator=()
template<class ... HandlerArgs> EventHandler< HandlerArgs... > & jaut::EventHandler< HandlerArgs >::operator= (EventHandler< HandlerArgs > right) noexcept
operator()()
template<class ... HandlerArgs> template<class ... Args> void jaut::EventHandler< HandlerArgs >::operator() (Args &&... args) const
Calls the stored callback.
This does not do a null-check, so be sure to check it yourself before calling it.
Parameters
args The arguments to pass to the callback
operator==()
template<class ... HandlerArgs> bool jaut::EventHandler< HandlerArgs >::operator== (const EventHandler< HandlerArgs > & handler) const noexcept
Compares two EventHandler and returns whether their callbacks are equal, or, in associative mode, their ids.
Note that when this handler is a closure or functor, this will always return false, as there is no reliable way of comparing them. (technically there is, but since they can be rvalues, their addresses would differ)
Parameters
handler The handler to compare this handler with
Returns
True if both handlers point to the same function, false otherwise
operator!=()
template<class ... HandlerArgs> bool jaut::EventHandler< HandlerArgs >::operator!= (const EventHandler< HandlerArgs > & handler) const noexcept
Compares two EventHandler and returns whether their callbacks are not equal.
Parameters
handler The handler to compare this handler with
Returns
True if both handlers point to different functions, false if not
References jaut::operator==().
isMemberFunction()
template<class ... HandlerArgs> bool jaut::EventHandler< HandlerArgs >::isMemberFunction () const noexcept
Determines whether the function this handler is pointing to is a member function.
Returns
True if it is a member function, otherwise false
isFreeFunction()
template<class ... HandlerArgs> bool jaut::EventHandler< HandlerArgs >::isFreeFunction () const noexcept
Determines whether the function this handler is pointing to is a free function.
Returns
True if it is a free function, otherwise false
isClosureOrFunctor()
template<class ... HandlerArgs> bool jaut::EventHandler< HandlerArgs >::isClosureOrFunctor () const noexcept
Determines whether the function this handler is pointing to is a functor or closure.
Returns
True if it is a closure or functor, otherwise false
isChained()
template<class ... HandlerArgs> bool jaut::EventHandler< HandlerArgs >::isChained () const noexcept
Determines whether this handler is a chained handler, that binds another event to this one.
Returns
True if this is a chained handler
isAssociative()
template<class ... HandlerArgs> bool jaut::EventHandler< HandlerArgs >::isAssociative () const noexcept
Determines whether this handler is an associative handler or not.
Returns
True if the handler possesses an id, otherwise false
getId()
template<class ... HandlerArgs> juce::String jaut::EventHandler< HandlerArgs >::getId () const noexcept
Gets the id of the handler if it is associative, otherwise an empty string.
Returns
The id of the handler
The documentation for this class was generated from the following file:
/github/workspace/modules/jaut_core/signal/event/jaut_Event.h