JAUT: jaut::detail Namespace Reference
jaut::detail Namespace Reference
Typedefs
template<class Replacements , class ... Types>
using replaceAllPlaceholders_t = typename replaceAllPlaceholders< Replacements, typeList<>, Types... >::type
template<class Left , class Right >
using isComparable_impl = decltype((std::declval< Left >()==std::declval< Right >()))
using FieldVec = std::vector< LogMessage::Field >
Functions
template<class T , class U , class Fn >
JAUT_NODISCARD SafeFloat::Result< T > safeFloatOperation (T left, U right, Fn &&func)
template<class Fn >
auto handlerResolverHelper (Fn &&fn)
template<class Fn , class ... Args>
auto handlerResolverHelper (Fn &&fn, handlerResolver< std::function< void(Args...)> >)
template<class Fn >
auto handlerResolverHelper (juce::String id, Fn &&fn)
template<class Fn , class ... Args>
auto handlerResolverHelper (juce::String id, Fn &&fn, handlerResolver< std::function< void(Args...)> >)
template<class Fn , class ... Args, int ... Indices, class TypeList = TypeArray<Args...>>
constexpr decltype(auto) filterArguments (std::integer_sequence< int, Indices... >, Fn &&invocable, std::tuple< Args... > &&tuple) noexcept(noexcept(std::forward< Fn >(invocable)(std::forward< typename TypeList::template at< Indices > >(std::get< Indices >(tuple))...)))
template<class T >
JAUT_NODISCARD juce::String addressToString (const T *ptr)
template<class Ret , class T , class ... Params>
constexpr TypeArray< Ret, T > getReturnAndClass (Ret(T::*)(Params...)) noexcept
template<class Ret , class ... Params>
constexpr TypeArray< Ret > getReturnAndClass (Ret(*)(Params...)) noexcept
template<class Field >
void emplaceField (std::vector< Field > &fieldList, Field &&field)
Variables
template<class T , bool Output = false>
constexpr bool dependentTypeAssert_v = dependentTypeAssert<T, Output>::value
template<auto V, bool Output = false>
constexpr bool dependentValueAssert_v = dependentValueAssert<V, Output>::value
template<class ... Args>
constexpr bool FmtEnableIfCheck_v = FmtEnableIfCheck<Args...>::value
Typedef Documentation
replaceAllPlaceholders_t
template<class Replacements , class ... Types> using jaut::detail::replaceAllPlaceholders_t = typedef typename replaceAllPlaceholders<Replacements, typeList<>, Types...>::type
isComparable_impl
template<class Left , class Right > using jaut::detail::isComparable_impl = typedef decltype((std::declval<Left>() == std::declval<Right>()))
FieldVec
using jaut::detail::FieldVec = typedef std::vector<LogMessage::Field>
Function Documentation
safeFloatOperation()
template<class T , class U , class Fn > JAUT_NODISCARD SafeFloat::Result< T > jaut::detail::safeFloatOperation (T left, U right, Fn && func)
References JAUT_ASSERT_SAFEFLOAT_NO_FLOAT_TYPE.
Referenced by jaut::SafeFloat::add(), jaut::SafeFloat::div(), jaut::SafeFloat::mod(), jaut::SafeFloat::mul(), and jaut::SafeFloat::sub().
handlerResolverHelper() [1/4]
template<class Fn > auto jaut::detail::handlerResolverHelper (Fn && fn)
References handlerResolverHelper().
Referenced by handlerResolverHelper(), handlerResolverHelper(), jaut::makeHandler(), and jaut::makeHandler().
handlerResolverHelper() [2/4]
template<class Fn , class ... Args> auto jaut::detail::handlerResolverHelper (Fn && fn, handlerResolver< std::function< void(Args...)> >)
handlerResolverHelper() [3/4]
template<class Fn > auto jaut::detail::handlerResolverHelper (juce::String id, Fn && fn)
References handlerResolverHelper().
handlerResolverHelper() [4/4]
template<class Fn , class ... Args> auto jaut::detail::handlerResolverHelper (juce::String id, Fn && fn, handlerResolver< std::function< void(Args...)> >)
filterArguments()
template<class Fn , class ... Args, int ... Indices, class TypeList = TypeArray<Args...>> constexpr decltype(auto) jaut::detail::filterArguments (std::integer_sequence< int, Indices... > , Fn && invocable, std::tuple< Args... > && tuple) constexpr noexcept
addressToString()
template<class T > JAUT_NODISCARD juce::String jaut::detail::addressToString (const T * ptr)
Referenced by jaut::Stringable< T * >::toString().
getReturnAndClass() [1/2]
template<class Ret , class T , class ... Params> constexpr TypeArray< Ret, T > jaut::detail::getReturnAndClass (Ret(T::*)(Params...)) constexpr noexcept
Referenced by getReturnAndClass().
getReturnAndClass() [2/2]
template<class Ret , class ... Params> constexpr TypeArray< Ret > jaut::detail::getReturnAndClass (Ret(*)(Params...)) constexpr noexcept
References getReturnAndClass().
emplaceField()
template<class Field > void jaut::detail::emplaceField (std::vector< Field > & fieldList, Field && field)
References jaut::LogMessage::Field::name, and jaut::LogMessage::Field::value.
Referenced by jaut::AbstractLogger::LogBuilder::operator<<().
Variable Documentation
dependentTypeAssert_v
template<class T , bool Output = false> constexpr bool jaut::detail::dependentTypeAssert_v = dependentTypeAssert<T, Output>::value constexpr
dependentValueAssert_v
template<auto V, bool Output = false> constexpr bool jaut::detail::dependentValueAssert_v = dependentValueAssert<V, Output>::value constexpr
FmtEnableIfCheck_v
template<class ... Args> constexpr bool jaut::detail::FmtEnableIfCheck_v = FmtEnableIfCheck<Args...>::value constexpr