JAUT: jaut::TypeArray<> Struct Reference
jaut::TypeArray<> Struct Reference
A useful type-list utility that declares a lot of useful helper functions to work on and with a list of types directly and convenient.
#include <jaut_TypeContainer.h>
Public Types
using clear = TypeArray
Gets an empty TypeArray.
template<template< class... > class T>
using to = T<>
Creates a new type of the types of this TypeArray.
using toVariant = std::variant< std::monostate >
Creates a variant type with the types of this TypeArray.
template<std::size_t N>
using toArray = std::array< toVariant, N >
Returns a variant array type with the types of this TypeArray.
template<class T >
using of = toTypeArray_t< T >
Creates a new TypeArray from another type-list.
template<std::size_t I>
using at = getTypeAt_t< TypeArray, I >
Gets the type at a specified index in this TypeArray.
template<class ... Add>
using add = TypeArray< Add... >
Adds the specified types to this TypeArray and returns a new one.
template<class ... Prepend>
using prepend = TypeArray< Prepend... >
Prepends the specified types to this TypeArray and returns a new one.
template<class ... Add>
using addIfAbsent = addIfAbsent_t< TypeArray, Add... >
Adds the specified types, that do not exist already, to this TypeArray and returns a new one.
template<class ... Remove>
using remove = TypeArray
Removes the specified types from this TypeArray and returns a new one.
template<class Predicate >
using removeIf = TypeArray
Removes the specified types from this TypeArray that meet the specified condition and returns a new one.
using front = EmptyType
Gets the first type of this TypeArray.
using back = EmptyType
Gets the last type of this TypeArray.
Static Public Member Functions
template<class Fn , class ... Args>
static constexpr void forEach (Args &&...args) noexcept
Calls a callback for each type contained in this TypeArray.
template<class Fn , class ... Args>
static constexpr void forEach (Fn &&functor, Args &&...args) noexcept
Calls a functor for each type contained in this TypeArray individually.
template<class Fn >
static constexpr void iterate (Fn &&callback) noexcept
template<class Fn , class ... Args>
static constexpr EmptyType forAll (Args &&...args) noexcept
Calls a functor exactly once with all types.
template<class Fn , class ... Args>
static constexpr EmptyType forAll (Fn &&func, Args &&...args) noexcept
Calls a functor exactly once with all types.
template<class ... Args>
static constexpr toArray< length > fillArray (Args &&...args) noexcept
Creates an std::array with an variant type and fills them in order the types appear.
template<std::size_t I, class ... Args>
static constexpr EmptyType construct (Args &&...args)
Constructs a new object from the type at the specified index.
template<std::size_t I, class Allocator = std::allocator<EmptyType>, class ... Args>
static EmptyType * allocate (Args &&...args)
Allocates a new object from the type at the specified index.
template<std::size_t I, class ... Args>
static std::unique_ptr< EmptyType > makeUnique (Args &&...args)
Creates a new std::unique_ptr from the type at the specified index.
template<std::size_t I, class ... Args>
static std::shared_ptr< EmptyType > makeShared (Args &&...args)
Creates a new std::shared_ptr from the type at the specified index.
Static Public Attributes
template<class Other >
static constexpr bool equals = std::is_same_v<TypeArray, Other>
Gets whether this TypeArray and the specified TypeArray are equal.
template<class Other >
static constexpr bool same = hasSameTypeList_v<TypeArray, Other>
Gets whether the type-list of this TypeArray and the specified type-list are equal.
static constexpr std::size_t size = 0
Gets the amount of types in this TypeArray.
static constexpr std::size_t length = 0
Gets the amount of types in this TypeArray.
static constexpr bool isEmpty = true
Gets whether this TypeArray contains any types.
template<class T >
static constexpr std::size_t indexOf = std::numeric_limits<std::size_t>::max()
Gets the index of the specified type in this TypeArray.
template<class T >
static constexpr bool contains = false
Gets whether this TypeArray contains the specified type.
Detailed Description
A useful type-list utility that declares a lot of useful helper functions to work on and with a list of types directly and convenient.
Template Parameters
Types The list of types
Member Typedef Documentation
clear
using jaut::TypeArray<>::clear = TypeArray
Gets an empty TypeArray.
to
template<template< class... > class T> using jaut::TypeArray<>::to = T<>
Creates a new type of the types of this TypeArray.
Template Parameters
T The class to adopt this' type-list
toVariant
using jaut::TypeArray<>::toVariant = std::variant<std::monostate>
Creates a variant type with the types of this TypeArray.
If the TypeArray is empty, the variant will be a std::monostate variant.
toArray
template<std::size_t N> using jaut::TypeArray<>::toArray = std::array<toVariant, N>
Returns a variant array type with the types of this TypeArray.
Template Parameters
N The size of the array
of
template<class T > using jaut::TypeArray<>::of = toTypeArray_t<T>
Creates a new TypeArray from another type-list.
Template Parameters
T The type-list to adopt the types from
at
template<std::size_t I> using jaut::TypeArray<>::at = getTypeAt_t<TypeArray, I>
Gets the type at a specified index in this TypeArray.
Template Parameters
I The index of the type to fetch
add
template<class ... Add> using jaut::TypeArray<>::add = TypeArray<Add...>
Adds the specified types to this TypeArray and returns a new one.
Template Parameters
Add The types to append to the end of the list
prepend
template<class ... Prepend> using jaut::TypeArray<>::prepend = TypeArray<Prepend...>
Prepends the specified types to this TypeArray and returns a new one.
Template Parameters
Prepend The types to prepend to the start of the list
addIfAbsent
template<class ... Add> using jaut::TypeArray<>::addIfAbsent = addIfAbsent_t<TypeArray, Add...>
Adds the specified types, that do not exist already, to this TypeArray and returns a new one.
Template Parameters
Add The types to append to the end of the list
remove
template<class ... Remove> using jaut::TypeArray<>::remove = TypeArray
Removes the specified types from this TypeArray and returns a new one.
Template Parameters
Remove The types to remove
removeIf
template<class Predicate > using jaut::TypeArray<>::removeIf = TypeArray
Removes the specified types from this TypeArray that meet the specified condition and returns a new one.
Template Parameters
Predicate The condition to be met
See also
jaut::Predicate
front
using jaut::TypeArray<>::front = EmptyType
Gets the first type of this TypeArray.
If the TypeArray is empty, this will return jaut::EmptyType.
back
using jaut::TypeArray<>::back = EmptyType
Gets the last type of this TypeArray.
If the TypeArray is empty, this will return jaut::EmptyType.
Member Function Documentation
forEach() [1/2]
template<class Fn , class ... Args> static constexpr void jaut::TypeArray<>::forEach (Args &&... args) static constexpr noexcept
Calls a callback for each type contained in this TypeArray.
The callback must be a functor:
using MyTypeList = jaut::TypeArray<int, double, float>;
struct MyFunctor
{
    template<class Type>
    void operator()(int test)
    {
        // Do stuff with Type
    }
}
// Later in code
MyTypeList::forEach<MyFunctor>(8);
Template Parameters
Fn The functor to be called
Parameters
args The arguments that will be passed to the functor
References jaut::ignore().
forEach() [2/2]
template<class Fn , class ... Args> static constexpr void jaut::TypeArray<>::forEach (Fn && functor, Args &&... args) static constexpr noexcept
Calls a functor for each type contained in this TypeArray individually.
The functor must be a functor like:
using MyTypeList = jaut::TypeArray<int, double, float>;
struct MyFunctor
{
    template<class Type>
    void operator()(int test)
    {
        // Do stuff with Type
    }
}
// Later in code
MyTypeList::forEach(MyFunctor(), 8);
Template Parameters
Fn The functor to be called
Parameters
func The functor instance to call
args The arguments that will be passed to the functor
References jaut::ignore().
iterate()
template<class Fn > static constexpr void jaut::TypeArray<>::iterate (Fn && callback) static constexpr noexcept
References jaut::ignore().
forAll() [1/2]
template<class Fn , class ... Args> static constexpr EmptyType jaut::TypeArray<>::forAll (Args &&... args) static constexpr noexcept
Calls a functor exactly once with all types.
Other than forEach, this does not call the functor individually for each single argument but rather all together which allows for parameter pack expansions.
The functor must be a functor like:
using MyTypeList = jaut::TypeArray<int, double, float>;
struct MyFunctor
{
    template<class ...Types>
    void operator()(int test)
    {
        // Do stuff with Types
    }
}
// Later in code
MyTypeList::forAll<MyFunctor>(8);
Template Parameters
Fn The functor to be called
Parameters
args The arguments that will be passed to the functor
Returns
The value that will be returned by the functor used
References jaut::ignore().
forAll() [2/2]
template<class Fn , class ... Args> static constexpr EmptyType jaut::TypeArray<>::forAll (Fn && func, Args &&... args) static constexpr noexcept
Calls a functor exactly once with all types.
Other than forEach, this does not call the functor individually for each single argument but rather all together which allows for parameter pack expansions.
The functor must be a functor like:
using MyTypeList = jaut::TypeArray<int, double, float>;
struct MyFunctor
{
    template<class ...Types>
    void operator()(int test)
    {
        // Do stuff with Types
    }
}
// Later in code
MyTypeList::forAll(MyFunctor(), 8);
Template Parameters
Fn The functor to be called
Parameters
functor The functor instance to call
args The arguments that will be passed to the functor
Returns
The value that will be returned by the functor used
References jaut::ignore().
fillArray()
template<class ... Args> static constexpr toArray< length > jaut::TypeArray<>::fillArray (Args &&... args) static constexpr noexcept
Creates an std::array with an variant type and fills them in order the types appear.
This only works if all types have at least one constructor that complies with the other types.
Parameters
args The constructor arguments each type should be constructed with
Returns
The filled std::array
References jaut::ignore().
construct()
template<std::size_t I, class ... Args> static constexpr EmptyType jaut::TypeArray<>::construct (Args &&... args) static constexpr
Constructs a new object from the type at the specified index.
Template Parameters
I The index of the type to construct
Parameters
args The arguments to parse to the constructor
Returns
The newly constructed object
References jaut::ignore().
allocate()
template<std::size_t I, class Allocator = std::allocator<EmptyType>, class ... Args> static EmptyType * jaut::TypeArray<>::allocate (Args &&... args) static
Allocates a new object from the type at the specified index.
Template Parameters
I The index of the type to construct
Parameters
args The arguments to parse to the constructor
Returns
The newly allocated object
References jaut::ignore().
makeUnique()
template<std::size_t I, class ... Args> static std::unique_ptr< EmptyType > jaut::TypeArray<>::makeUnique (Args &&... args) static
Creates a new std::unique_ptr from the type at the specified index.
Template Parameters
I The index of the type to construct
Parameters
args The arguments to parse to the constructor
Returns
The std::unique_ptr object
References jaut::ignore().
makeShared()
template<std::size_t I, class ... Args> static std::shared_ptr< EmptyType > jaut::TypeArray<>::makeShared (Args &&... args) static
Creates a new std::shared_ptr from the type at the specified index.
Template Parameters
I The index of the type to construct
Parameters
args The arguments to parse to the constructor
Returns
The std::shared_ptr object
References jaut::ignore().
Member Data Documentation
equals
template<class Other > constexpr bool jaut::TypeArray<>::equals = std::is_same_v<TypeArray, Other> static constexpr
Gets whether this TypeArray and the specified TypeArray are equal.
Template Parameters
Other The TypeArray to check against
same
template<class Other > constexpr bool jaut::TypeArray<>::same = hasSameTypeList_v<TypeArray, Other> static constexpr
Gets whether the type-list of this TypeArray and the specified type-list are equal.
Template Parameters
Other The TypeArray to check against
size
constexpr std::size_t jaut::TypeArray<>::size = 0 static constexpr
Gets the amount of types in this TypeArray.
This is the same as jaut::TypeArray::length.
length
constexpr std::size_t jaut::TypeArray<>::length = 0 static constexpr
Gets the amount of types in this TypeArray.
This is the same as jaut::TypeArray::size.
isEmpty
constexpr bool jaut::TypeArray<>::isEmpty = true static constexpr
Gets whether this TypeArray contains any types.
indexOf
template<class T > constexpr std::size_t jaut::TypeArray<>::indexOf = std::numeric_limits<std::size_t>::max() static constexpr
Gets the index of the specified type in this TypeArray.
If the TypeArray is empty, this will return std::numeric_limits<std::size_t>::max().
Template Parameters
T The type to find the index for
contains
template<class T > constexpr bool jaut::TypeArray<>::contains = false static constexpr
Gets whether this TypeArray contains the specified type.
Template Parameters
T The type to be found
The documentation for this struct was generated from the following file:
/github/workspace/modules/jaut_core/util/jaut_TypeContainer.h