JAUT: jaut::SafeFloat Struct Reference
jaut::SafeFloat Struct Reference
#include <jaut_SafeFloat.h>
Classes
struct Result
Public Member Functions
template<class T , class U >
SafeFloat::Result< T > cast (U value)
template<class T , class U >
SafeFloat::Result< T > add (T left, U right)
template<class T , class U >
SafeFloat::Result< T > sub (T left, U right)
template<class T , class U >
SafeFloat::Result< T > mul (T left, U right)
template<class T , class U >
SafeFloat::Result< T > div (T left, U right)
template<class T , class U >
SafeFloat::Result< T > mod (T left, U right)
template<class T , class U >
bool equals (T left, U right) noexcept
template<class T , class U >
bool notEquals (T left, U right) noexcept
template<class T , class U >
bool greaterThan (T left, U right) noexcept
template<class T , class U >
bool smallerThan (T left, U right) noexcept
template<class T , class U >
bool greaterThanOrEquals (T left, U right) noexcept
template<class T , class U >
bool smallerThanOrEquals (T left, U right) noexcept
Static Public Member Functions
template<class T , class U >
static JAUT_NODISCARD Result< T > cast (U value)
Tries to cast U to T.
template<class T , class U >
static JAUT_NODISCARD Result< T > add (T left, U right)
Tries to add left with right.
template<class T , class U >
static JAUT_NODISCARD Result< T > sub (T left, U right)
Tries to subtract right from left.
template<class T , class U >
static JAUT_NODISCARD Result< T > mul (T left, U right)
Tries to multiply left with right.
template<class T , class U >
static JAUT_NODISCARD Result< T > div (T left, U right)
Tries to divide left by right.
template<class T , class U >
static JAUT_NODISCARD Result< T > mod (T left, U right)
Tries to divide left by right.
template<class T , class U >
static JAUT_NODISCARD bool equals (T left, U right) noexcept
Tries to safely check for equality of left and right.
template<class T , class U >
static JAUT_NODISCARD bool notEquals (T left, U right) noexcept
Tries to safely check for non-equality of left and right.
template<class T , class U >
static JAUT_NODISCARD bool greaterThan (T left, U right) noexcept
Tries to safely check if left is greater than right.
template<class T , class U >
static JAUT_NODISCARD bool smallerThan (T left, U right) noexcept
Tries to safely check if left is smaller than right.
template<class T , class U >
static JAUT_NODISCARD bool greaterThanOrEquals (T left, U right) noexcept
Tries to safely check if left is greater or equal to right.
template<class T , class U >
static JAUT_NODISCARD bool smallerThanOrEquals (T left, U right) noexcept
Tries to safely check if left is smaller or equal to right.
Member Function Documentation
cast() [1/2]
template<class T , class U > static JAUT_NODISCARD Result< T > jaut::SafeFloat::cast (U value) static
Tries to cast U to T.
Returns the casted value or 0 if the cast went wrong.
Template Parameters
T The type to cast to
Parameters
value The value to cast to T
Returns
The result of the operation
add() [1/2]
template<class T , class U > static JAUT_NODISCARD Result< T > jaut::SafeFloat::add (T left, U right) static
Tries to add left with right.
Returns the sum or left if an overflow has happened.
Parameters
left The left-hand operand
right The right-hand operand
Returns
The result of the operation
sub() [1/2]
template<class T , class U > static JAUT_NODISCARD Result< T > jaut::SafeFloat::sub (T left, U right) static
Tries to subtract right from left.
Returns the difference or left if an overflow has happened.
Parameters
left The left-hand operand
right The right-hand operand
Returns
The result of the operation
mul() [1/2]
template<class T , class U > static JAUT_NODISCARD Result< T > jaut::SafeFloat::mul (T left, U right) static
Tries to multiply left with right.
Returns the product or left if an overflow has happened.
Parameters
left The left-hand operand
right The right-hand operand
Returns
The result of the operation
div() [1/2]
template<class T , class U > static JAUT_NODISCARD Result< T > jaut::SafeFloat::div (T left, U right) static
Tries to divide left by right.
Returns the quotient or left if an overflow or a division-by-zero has happened.
Parameters
left The left-hand operand
right The right-hand operand
Returns
The result of the operation
mod() [1/2]
template<class T , class U > static JAUT_NODISCARD Result< T > jaut::SafeFloat::mod (T left, U right) static
Tries to divide left by right.
Returns the remainder or left if an overflow or a division-by-zero has happened.
Parameters
left The left-hand operand
right The right-hand operand
Returns
The result of the operation
equals() [1/2]
template<class T , class U > static JAUT_NODISCARD bool jaut::SafeFloat::equals (T left, U right) static noexcept
Tries to safely check for equality of left and right.
Note that this only allows comparison of floating-point types with any other type, it does not guarantee a more accurate comparison result.
Parameters
left The left-hand operand
right The right-hand operand
Returns
True if they are equal, otherwise false
notEquals() [1/2]
template<class T , class U > static JAUT_NODISCARD bool jaut::SafeFloat::notEquals (T left, U right) static noexcept
Tries to safely check for non-equality of left and right.
Note that this only allows comparison of floating-point types with any other type, it does not guarantee a more accurate comparison result.
Parameters
left The left-hand operand
right The right-hand operand
Returns
True if they are not equal, otherwise false
greaterThan() [1/2]
template<class T , class U > static JAUT_NODISCARD bool jaut::SafeFloat::greaterThan (T left, U right) static noexcept
Tries to safely check if left is greater than right.
Note that this only allows comparison of floating-point types with any other type, it does not guarantee a more accurate comparison result.
Parameters
left The left-hand operand
right The right-hand operand
Returns
True if left is greater, otherwise false
smallerThan() [1/2]
template<class T , class U > static JAUT_NODISCARD bool jaut::SafeFloat::smallerThan (T left, U right) static noexcept
Tries to safely check if left is smaller than right.
Note that this only allows comparison of floating-point types with any other type, it does not guarantee a more accurate comparison result.
Parameters
left The left-hand operand
right The right-hand operand
Returns
True if left is smaller, otherwise false
greaterThanOrEquals() [1/2]
template<class T , class U > static JAUT_NODISCARD bool jaut::SafeFloat::greaterThanOrEquals (T left, U right) static noexcept
Tries to safely check if left is greater or equal to right.
Note that this only allows comparison of floating-point types with any other type, it does not guarantee a more accurate comparison result.
Parameters
left The left-hand operand
right The right-hand operand
Returns
True if left is greater or equal, otherwise false
smallerThanOrEquals() [1/2]
template<class T , class U > static JAUT_NODISCARD bool jaut::SafeFloat::smallerThanOrEquals (T left, U right) static noexcept
Tries to safely check if left is smaller or equal to right.
Note that this only allows comparison of floating-point types with any other type, it does not guarantee a more accurate comparison result.
Parameters
left The left-hand operand
right The right-hand operand
Returns
True if left is smaller or equal, otherwise false
cast() [2/2]
template<class T , class U > SafeFloat::Result< T > jaut::SafeFloat::cast (U value)
References JAUT_ASSERT_SAFEFLOAT_NO_FLOAT_TYPE.
add() [2/2]
template<class T , class U > SafeFloat::Result< T > jaut::SafeFloat::add (T left, U right)
References jaut::detail::safeFloatOperation().
sub() [2/2]
template<class T , class U > SafeFloat::Result< T > jaut::SafeFloat::sub (T left, U right)
References jaut::detail::safeFloatOperation().
mul() [2/2]
template<class T , class U > SafeFloat::Result< T > jaut::SafeFloat::mul (T left, U right)
References jaut::detail::safeFloatOperation().
div() [2/2]
template<class T , class U > SafeFloat::Result< T > jaut::SafeFloat::div (T left, U right)
References jaut::detail::safeFloatOperation().
mod() [2/2]
template<class T , class U > SafeFloat::Result< T > jaut::SafeFloat::mod (T left, U right)
References jaut::detail::safeFloatOperation().
equals() [2/2]
template<class T , class U > bool jaut::SafeFloat::equals (T left, U right) noexcept
notEquals() [2/2]
template<class T , class U > bool jaut::SafeFloat::notEquals (T left, U right) noexcept
greaterThan() [2/2]
template<class T , class U > bool jaut::SafeFloat::greaterThan (T left, U right) noexcept
smallerThan() [2/2]
template<class T , class U > bool jaut::SafeFloat::smallerThan (T left, U right) noexcept
greaterThanOrEquals() [2/2]
template<class T , class U > bool jaut::SafeFloat::greaterThanOrEquals (T left, U right) noexcept
smallerThanOrEquals() [2/2]
template<class T , class U > bool jaut::SafeFloat::smallerThanOrEquals (T left, U right) noexcept
The documentation for this struct was generated from the following file:
/github/workspace/modules/jaut_core/math/jaut_SafeFloat.h