JAUT: jaut::MessageHandler< BufferSize, BackBufferSize > Class Template Reference
jaut::MessageHandler< BufferSize, BackBufferSize > Class Template Reference
A simple implementation of an thread synchronisation manager.
#include <jaut_MessageHandler.h>
Classes
struct Options
Declares a few options for the MessageHandler class.
Public Types
using BufferType = AtomicRingBuffer< BufferSize >
using MessagePointer = typename BufferType::Message
using DeferredMessageInitHandler = std::function< bool(IMessage *)>
The deferred message init policies callback type.
Public Member Functions
MessageHandler (Options options=Options())
Constructs a new MessageHandler instance.
void send (NonNull< MessagePointer > message)
Schedules a new message for the target-thread and pushes it into the message buffer.
void send (NonNull< message::MessageCallback::CallbackHandler > callback)
Schedules a new message for the target-thread and pushes it into the message buffer.
template<class MessageType , class... Args>
void send (Args &&...args)
Schedules a new message for the target-thread and pushes it into the message buffer.
void sendAll (std::vector< NonNull< MessagePointer > > messages)
Schedules a list of messages to send to the target-thread and pushes them into the buffer.
void sendAll (std::vector< NonNull< message::MessageCallback::CallbackHandler > > messages)
Schedules a list of messages to send to the target-thread and pushes them into the buffer.
JAUT_NODISCARD bool hasPendingMessages () const noexcept
Returns whether there are any pending messages in the message to target buffer.
void processNextMessage ()
Processes the next message in the buffer to the target-thread and calls handleMessage().
void processAllMessages ()
Processes all messages in the buffer to the target-thread and calls handleMessage().
void cancelPendingMessages ()
Cancels all pending messages in the buffer to the target currently scheduled.
Public Attributes
DeferredMessageInitHandler deferredMessageInitHandler = [](IMessage*){ return true; }
Defines the callback for initialising deferred messages on the audio thread to be sent back to the message thread and handled there.
Static Public Attributes
static constexpr int bufferSize = BufferSize
static constexpr int backBufferSize = BackBufferSize
Protected Member Functions
virtual void handleMessage (IMessage *message, MessageDirection direction)
Handles the message.
Detailed Description
template<int BufferSize = 16, int BackBufferSize = static_cast<int>(BufferSize * 1.5)>
class jaut::MessageHandler< BufferSize, BackBufferSize >
A simple implementation of an thread synchronisation manager.
The MessageHandler class helps sending messages from the message-thread to any other (real-time) thread.
To get started with this class, simply inherit from this class and, if needed, override handleMessage(IMessage*, MessageDirection) if message receiving needs to be handled manually.
The back-buffer serves in two ways, one is as garbage collector and another is sending messages to the message thread.
Template Parameters
BufferSize The size of the message buffer and the garbage collector
BackBufferSize The size of the message buffer that goes from the target to the message thread
Member Typedef Documentation
BufferType
template<int BufferSize = 16, int BackBufferSize = static_cast<int>(BufferSize * 1.5)> using jaut::MessageHandler< BufferSize, BackBufferSize >::BufferType = AtomicRingBuffer<BufferSize>
MessagePointer
template<int BufferSize = 16, int BackBufferSize = static_cast<int>(BufferSize * 1.5)> using jaut::MessageHandler< BufferSize, BackBufferSize >::MessagePointer = typename BufferType::Message
DeferredMessageInitHandler
template<int BufferSize = 16, int BackBufferSize = static_cast<int>(BufferSize * 1.5)> using jaut::MessageHandler< BufferSize, BackBufferSize >::DeferredMessageInitHandler = std::function<bool(IMessage*)>
The deferred message init policies callback type.
Constructor & Destructor Documentation
MessageHandler()
template<int N, int M> jaut::MessageHandler< N, M >::MessageHandler (Options options = Options()) explicit
Constructs a new MessageHandler instance.
Parameters
options The options for this MessageHandler instance
Exceptions
std::logic_error If the policies is not owned by the message thread
References jaut::MessageHandler< BufferSize, BackBufferSize >::Options::deferredAndGCInterval.
Member Function Documentation
send() [1/3]
template<int N, int M> void jaut::MessageHandler< N, M >::send (NonNull< MessagePointer > message)
Schedules a new message for the target-thread and pushes it into the message buffer.
If the message buffer is full, it will return false.
This will start the garbage collector if it wasn't scheduled already.
Note: You shouldn't call this on a real-time thread as it locks to get the thread it is on.
Parameters
message The message to send to the target-thread
Exceptions
jaut::QueueSpaceExceededException If the queue was full
References jaut::NonNull< T >::get().
send() [2/3]
template<int N, int M> void jaut::MessageHandler< N, M >::send (NonNull< message::MessageCallback::CallbackHandler > callback)
Schedules a new message for the target-thread and pushes it into the message buffer.
If the message buffer is full, this won't do anything.
This will start the garbage collector if it wasn't scheduled already.
Note: You shouldn't call this on a real-time thread as it locks to get the thread it is on.
Parameters
message The message to send to the target-thread
Exceptions
jaut::QueueSpaceExceededException If the queue was full
References jaut::NonNull< T >::get().
send() [3/3]
template<int N, int M> template<class MessageType , class... Args> void jaut::MessageHandler< N, M >::send (Args &&... args)
Schedules a new message for the target-thread and pushes it into the message buffer.
If the message buffer is full, this won't do anything.
This will start the garbage collector if it wasn't scheduled already.
Other than send(std::shared_ptr<IMessage>), this constructs a new message from its constructor's parameters and pushes it into the buffer. You should always prefer this function over the other.
Note: You shouldn't call this on a real-time thread as it locks to get the thread it is on.
Template Parameters
MessageType The message class
Parameters
args The arguments to pass to the message's constructor
Exceptions
jaut::QueueSpaceExceededException If the queue was full
sendAll() [1/2]
template<int N, int M> void jaut::MessageHandler< N, M >::sendAll (std::vector< NonNull< MessagePointer > > messages)
Schedules a list of messages to send to the target-thread and pushes them into the buffer.
All the messages that don't fit into the buffer anymore, will be ignored and destroyed.
This will start the garbage collector if it wasn't scheduled already.
Note: You shouldn't call this on a real-time thread as it locks to get the thread it is on.
Parameters
messages The list of messages to schedule
Exceptions
jaut::QueueSpaceExceededException If the queue was full
sendAll() [2/2]
template<int N, int M> void jaut::MessageHandler< N, M >::sendAll (std::vector< NonNull< message::MessageCallback::CallbackHandler > > messages)
Schedules a list of messages to send to the target-thread and pushes them into the buffer.
All the messages that don't fit into the buffer anymore, will be ignored and destroyed.
This will start the garbage collector if it wasn't scheduled already.
Note: You shouldn't call this on a real-time thread as it locks to get the thread it is on.
Parameters
messages The list of messages to schedule
Exceptions
jaut::QueueSpaceExceededException If the queue was full
hasPendingMessages()
template<int N, int M> bool jaut::MessageHandler< N, M >::hasPendingMessages noexcept
Returns whether there are any pending messages in the message to target buffer.
Returns
True if there are messages in the buffer, false if not
processNextMessage()
template<int N, int M> void jaut::MessageHandler< N, M >::processNextMessage
Processes the next message in the buffer to the target-thread and calls handleMessage().
After the message was handled, it will, if and only if the garbage collector is enabled, push it into the garbage collector and schedule it for disposal.
processAllMessages()
template<int N, int M> void jaut::MessageHandler< N, M >::processAllMessages
Processes all messages in the buffer to the target-thread and calls handleMessage().
After the message was handled, it will, if and only if the garbage collector is enabled, push it into the garbage collector and schedule it for disposal.
cancelPendingMessages()
template<int N, int M> void jaut::MessageHandler< N, M >::cancelPendingMessages
Cancels all pending messages in the buffer to the target currently scheduled.
If there are no messages, this will do nothing.
Note: You shouldn't call this on a real-time thread as it locks to get the thread it is on.
handleMessage()
template<int N, int M> void jaut::MessageHandler< N, M >::handleMessage (IMessage * message, MessageDirection direction) protected virtual
Handles the message.
This can be override, if needed for cases where messages need to be intercepted. However, only do that if you know what you are doing.
Parameters
message The message to handle
direction The thread the message was handled on
References jaut::IMessage::handleMessage().
Member Data Documentation
bufferSize
template<int BufferSize = 16, int BackBufferSize = static_cast<int>(BufferSize * 1.5)> constexpr int jaut::MessageHandler< BufferSize, BackBufferSize >::bufferSize = BufferSize static constexpr
backBufferSize
template<int BufferSize = 16, int BackBufferSize = static_cast<int>(BufferSize * 1.5)> constexpr int jaut::MessageHandler< BufferSize, BackBufferSize >::backBufferSize = BackBufferSize static constexpr
deferredMessageInitHandler
template<int BufferSize = 16, int BackBufferSize = static_cast<int>(BufferSize * 1.5)> DeferredMessageInitHandler jaut::MessageHandler< BufferSize, BackBufferSize >::deferredMessageInitHandler = [](IMessage*){ return true; }
Defines the callback for initialising deferred messages on the audio thread to be sent back to the message thread and handled there.
If this callback returns true, then the message will be enqueued for the message thread, returning false however cancels the message and it will be returned to be garbage collected.
The documentation for this class was generated from the following file:
/github/workspace/modules/jaut_message/thread/jaut_MessageHandler.h