JAUT: jaut Namespace Reference
jaut Namespace Reference
Namespaces
namespace message
Classes
class AbstractLogger
A simple and lightweight Logger implementation that aims at being a bit more advanced than the juce one.
struct addIfAbsent
Adds a type to a type-list if it isn't already contained.
struct addIfAbsent< T< Types... >, Add... >
struct allowsBitOperations
Checks whether T and U are valid operations for a bit-wise expression.
struct ArgFilter
Provides a filter for variadic function templates, which allows, based on the given predicate, to filter out a set of arguments and process them whatever way needed.
class AtomicRingBuffer
A simple SPSC queue implementation that allows pushing and popping from two different threads.
class AudioProcessorRack
The rack processor keeps an internal collection of AudioProcessor objects and plays them either in series or as single processors.
class AudioProcessorSet
The set processor allows to define a static set of processors that will be processed at processing time.
class BasicLogger
A proper logging implementation that aims at being a bit more advanced than the juce native one.
struct Cid
Describes the composition of a colour id as used in JUCE.
struct CidNamespace
Declares a unique namespace for colours of your library or app.
class Config
The Config class provides a toolset for reading/writing from/to config files on the local file system.
class ConfigIncompatibleTypeException
class ConfigIOException
class ConfigParseException
class ConfigPropertyIdException
class ContentPane
A simple component that contains another component and stretches it to a parent.
struct DefaultCase
struct Distance
A simple extension to juce::Rectangle that can be used for algorithmic padding, margin as it is the case in CSS environments.
struct DistanceUtil
struct EmptyType
The type to be returned by TypeArray<> operations that can't be made on an empty TypeArray.
class Event
The Event class provides a simple way for listeners to subscribe to events and changes that may occur.
class EventHandler
The EventHandler class stores a callback to a function and makes it invocable and storable in an Event object.
class ExtraComponent
A juce::Component implementation that allows basic styling of a component, such as borders margin and padding, and much more.
struct FlushPolicy
Determines the policy-type for when the buffer should be flushed to the output.
class FormatAttributes
class FormatLayout
struct Function< Func >
struct getIndexOf
Gets the index of the first matching type in the given type-list.
struct getIndexOf< T< Types... >, Key >
struct getTypeAt
Gets a type of a type-list at the specified index.
struct getTypeAt< T< Types... >, I >
struct getTypeListLength
Gets the amount of types in a type-list.
struct getTypeListLength< T< Args... > >
struct hasArguments
Checks whether type T's template list is empty or not.
struct hasArguments< T< Types... > >
struct hasArguments< T< Vals... > >
struct hasSameTypeList
Gets whether the type-list of two different classes are equal.
struct hasSameTypeList< T< Types... >, U< Types... > >
struct hasSameTypeList< T< Vals... >, U< Vals... > >
struct hasTemplateType
Checks whether a given type-list contains a specific type at least once.
struct hasTemplateType< T< Types... >, Key >
struct IConfigParser
An interfaces to provide the bare-bones for a new parser class to use in the jaut::Config class.
struct ILogFormat
Provides an interface for custom and inbuilt sink formatters.
struct ILogSink
Sinks are the actual output implementations, they will be there to map a logger to an output stream.
struct ILogWorker
A worker is a separate layer to a jaut::BasicLogger, used to actually transport messages to the logging sinks.
struct IMessage
Implements a message policies that should be passed on to the policies.
struct IMessageBuffer
The IMessageBuffer interface declares all needed virtual functions to craft your own message buffer.
struct IMessageHandler
struct isEqualityComparable
Checks whether two types are equality comparable.
struct isEqualityComparable< Left, Right, std::void_t< detail::isComparable_impl< Left, Right > > >
struct ISerialisableAudioProcessor
A simple interface class for sub-audio processors for your own processor implementation.
struct isHandlerFreeFunction
A type representing whether a function is a free function pointer complying to the specified jaut::EventHandler type.
struct isHandlerLambdaOrFunctor
A type representing whether a type is either a valid lambda-closure or a functor type complying to the specified jaut::EventHandler type.
struct isIterator
struct isIterator< T, std::enable_if_t<!std::is_same_v< std::iterator_traits< T >::value_type, void > > >
struct isPredicate
Determines whether the passed type is a jaut::PredicateX type.
struct isPredicate< Predicate< Args... > >
struct isPredicate< PredicateAnd< Args... > >
struct isPredicate< PredicateNot< Args... > >
struct isPredicate< PredicateOr< Args... > >
struct isPredicate< PredicateXor< Args... > >
struct isTemplated
Checks whether type T is a templated type or not.
struct isTemplated< T< Args... > >
struct isTemplated< T< Vals... > >
struct isValidNumeric
Checks whether T is a valid type for this wrapper.
class JsonParser
The JsonParser is an in-built parser for the Config class used for parsing Json style config files.
struct LambdaType
class LogFormatCallback
A simple formatter that can be used via a passed in lambda function or other invocable.
class LogFormatJson
Provides a json formatter that will log all events as json objects.
class LogFormatPattern
Provides a simple and straightforward fmt pattern formatter.
class LogFormatXml
Provides a json formatter that will log all events as json objects.
class LogIOException
struct LogLevel
The log level to produce.
struct LogMessage
The message container a single log-entry will be composed off.
class LogRotationException
class LogRotationManager
This class helps managing log files and how they should be rotated.
class LogSinkFile
A Logger output sink for log files.
class LogSinkOstream
A Logger output sink for the standard std::ostream.
class LogSinkRotatingFile
A Logger output sink for log files.
class LogWorkerAsync
The async log worker, which works asynchronously to the threads the logger is used by.
class LogWorkerSimple
The simple log worker which works synchronously to the thread the logger is owned by.
class LookAndFeel
class MessageHandler
A simple implementation of an thread synchronisation manager.
class MultiPagePanel
An extremely customisable component that lets you add pages that will be controlled by a tab bar.
class NonNull
Allows to pass a pointer that should not be assigned nullptr.
class Numeric
An numeric base class for classes that need to be arithmetically operable.
class OperationResult
A wrapper around an int and an optional error message providing result information of an operation with a specific error code.
struct Overload< Ret(Params...) & >
struct Overload< Ret(Params...) && >
struct Overload< Ret(Params...) const & >
struct Overload< Ret(Params...) const && >
struct Overload< Ret(Params...) const >
struct Overload< Ret(Params...) const volatile & >
struct Overload< Ret(Params...) const volatile && >
struct Overload< Ret(Params...) const volatile >
struct Overload< Ret(Params...) volatile & >
struct Overload< Ret(Params...) volatile && >
struct Overload< Ret(Params...) volatile >
struct Overload< Ret(Params...)>
class PolicyCombined
A combined policy.
class PolicyDaily
A scheduled rotation policy, this will rotate the log file at the specified time.
class PolicyPeriodic
A timed rotation policies, this will rotate the log file at the specified interval.
class PolicySizeLimit
Rotation policy that rotates the logs before a certain file size has been reached or exceeded.
struct Predicate
A delegated condition that will be checked later instead of immediate validation.
struct PredicateAnd
Collates several conditions and returns true if all conditions meet their requirements.
struct PredicateNot
Returns true if the condition evaluated to false.
struct PredicateOr
Collates several conditions and returns true if at least one of the conditions meet their requirements.
struct PredicateXor
Collates two conditions and returns true if only one of the conditions meet their requirements.
struct ProcessSpec
A quick wrapper class which gets passed to jaut::ISerialisableAudioProcessor::prepare(ProcessSpec).
struct PType
A placeholder used for jaut::Predicate to be replaced with a different type later on while operating.
struct qualifiesAsString
Checks whether type T could qualify as a string type.
struct qualifiesAsString< T< Types... > >
class QueueSpaceExceededException
Gets thrown inside jaut::MessageHandler if pushing another message could not be done due to lack of space.
struct removeFrom
Removes a specified type from a type-list if it exists and gives back the type-list without it.
struct removeFrom< T< Types... >, Remove... >
struct removeIf
Removes all types from the type-list that match the given predicate.
struct removeIf< T< Types... >, Pred >
struct replaceType
Replaces a specific type from the type-list of a class with another.
struct replaceType< T< Types... >, Key, Replacement >
struct RotationPolicyArgs
The arguments passed to a rotation policy to which the next rotation action should be determined from.
class RwLockGuard
struct SafeFloat
struct SafeInteger
struct sameTypeIgnoreTemplate
Determines whether TypeToCheck is of same type as TemplatedType.
struct sameTypeIgnoreTemplate< T, T< Types... > >
class ScopedCursor
A little utility that sets a mouse cursor and resets it to another once this object leaves the scope it is in.
struct ScopedCursorWait
Sets the current cursor to the wait cursor and resets it back to the normal one.
class ScopedSubscriber
A simple RAII event subscriber interface, that let's you automatically subscribe to and unsubscribe from an event.
class SerialisableJuceProcessorProxy
The SerialisableJuceProcessorProxy is an ISerializableAudioProcessor wrapper that wraps any other instance of an AudioProcessor into a sort of shell-like structure, that will act as if the encapsulated AudioProcessor was a SerializableAudioProcessor from the beginning.
struct shared_construct_t
A type used for optional function overloads to instruct to allocate the object as std::shared_ptr.
class SimpleRingBuffer
A simple queue implementation that allows pushing and popping from single threads.
struct Size
A convenience wrapper around two numeric types, that represent a size of some sorts.
class SplitPanel
A component that contains two components that can be resized with a separator in-between.
class StrategyPattern
A strategy that rotates the log files in a certain pattern.
struct Stringable
Defines a customisable template specialisation provider that allows you to convert objects to juce::String.
struct Stringable< bool >
struct Stringable< detail::MissingObjectProxy< T > >
struct Stringable< detail::MissingTypeNameProxy< T > >
struct Stringable< juce::ArgumentList >
struct Stringable< juce::ArgumentList::Argument >
struct Stringable< juce::Array< T, CS, N > >
struct Stringable< juce::ArrayBase< T, Ect... > >
struct Stringable< juce::Atomic< T > >
struct Stringable< juce::BigInteger >
struct Stringable< juce::DynamicObject >
struct Stringable< juce::File >
struct Stringable< juce::HashMap< T, U, Ect... > >
struct Stringable< juce::NamedValueSet >
struct Stringable< juce::NormalisableRange< T > >
struct Stringable< juce::OwnedArray< T, Ect... > >
struct Stringable< juce::PropertySet >
struct Stringable< juce::Range< T > >
struct Stringable< juce::SortedSet< T, Ect... > >
struct Stringable< juce::SparseSet< T > >
struct Stringable< juce::StringArray >
struct Stringable< juce::StringPairArray >
struct Stringable< juce::SystemStats >
struct Stringable< juce::URL >
struct Stringable< juce::Uuid >
struct Stringable< juce::var >
struct Stringable< LogMessage >
struct Stringable< LogMessage::ExceptionSpec >
struct Stringable< LogMessage::Field >
struct Stringable< Numeric< T, V > >
struct Stringable< std::array< T, N > >
struct Stringable< std::basic_string_view< T, Ect... > >
struct Stringable< std::deque< T, Ect... > >
struct Stringable< std::list< T, Ect... > >
struct Stringable< std::map< T, U, Ect... > >
struct Stringable< std::multimap< T, U, Ect... > >
struct Stringable< std::multiset< T, Ect... > >
struct Stringable< std::nullptr_t >
struct Stringable< std::set< T, Ect... > >
struct Stringable< std::thread::id >
struct Stringable< std::unordered_map< T, U, Ect... > >
struct Stringable< std::unordered_multimap< T, U, Ect... > >
struct Stringable< std::unordered_multiset< T, Ect... > >
struct Stringable< std::unordered_set< T, Ect... > >
struct Stringable< std::vector< T, Ect... > >
struct Stringable< T * >
struct Stringable< T *& >
struct Stringable< Version >
struct toTypeArray< T< Types... > >
struct TView
A dirty type previewer that will work in lots of IDEs.
struct TypeArray
A useful type-list utility that declares a lot of useful helper functions to work on and with a list of types directly and convenient.
struct TypeArray<>
A useful type-list utility that declares a lot of useful helper functions to work on and with a list of types directly and convenient.
struct TypeArrayIndex
struct TypeCase
struct TypeLadder
struct unique_construct_t
A type used for optional function overloads to instruct to allocate the object as std::unique_ptr.
class ValueParameterAttachment
A simple new parameter attachment type that allows attaching juce::Value objects to parameters.
class VarUtil
class Version
A versioning helper that wraps around different versioning components.
struct VView
A dirty value previewer that will work in lots of IDEs.
class XmlParser
The XmlParser is an in-built parser for the Config class used for parsing Xml style config files.
Typedefs
using TrivialHandler = EventHandler<>
An EventHandler with no arguments.
template<class Ret , class ... Types>
using FunctionPointer_t = Ret(*)(Types...)
A convenience type-wrapper for function pointers.
template<class Obj , class Ret , class ... Types>
using MemberFunctionPointer_t = Ret(Obj::*)(Types...)
A convenience type-wrapper for pointer-to-member functions.
template<class Obj , class T >
using MemberDataPointer_t = T Obj::*
A convenience type-wrapper for pointer-to-member objects.
template<class T >
using toTypeArray_t = typename toTypeArray< T >::type
Converts any type-list to a jaut::TypeArray.
template<class T , class Key , class Replacement >
using replaceType_t = typename replaceType< T, Key, Replacement >::type
Replaces a specific type from the type-list of a class with another.
template<class T , std::size_t I>
using getTypeAt_t = typename getTypeAt< T, I >::type
Gets a type of a type-list at the specified index.
template<class T , class ... Remove>
using removeFrom_t = typename removeFrom< T, Remove... >::type
Removes a specified type from a type-list if it exists and gets the new version.
template<class T , class Predicate >
using removeIf_t = typename removeIf< T, Predicate >::type
Removes all types from the type-list that match the given predicate.
template<class T , class ... Add>
using addIfAbsent_t = typename addIfAbsent< T, Add... >::type
Adds a type to a type-list if it isn't already contained.
template<class ... Cases>
using TypeLadder_t = typename TypeLadder< Cases... >::type
using CidnsJuce = detail::CidNamespaceInternal< Cid::Juce >
The namespace for JUCE colour IDs.
using CidnsJaut = detail::CidNamespaceInternal< Cid::Jaut >
The namespace for JAUT colour IDs.
template<class T >
using Thickness = Distance< T >
Specifies the thickness of a border or outline.
template<class T >
using Margin = Distance< T >
Specifies the distance from the outside of a component to the border of its parent.
template<class T >
using Padding = Distance< T >
Specifies the distance from the inside of a component to all its children.
using LoggerSimple = BasicLogger< LogWorkerSimple<> >
The default sync logger, this will make message processing happen on the same thread as the logging.
using LoggerAsync = BasicLogger< LogWorkerAsync<> >
The async logger, this will create a separate thread that will process the logging messages asynchronously.
template<int BufferSize>
using LoggerSimpleCS = BasicLogger< LogWorkerSimple< BufferSize > >
The default sync logger, this will make message processing happen on the same thread as the logging.
template<int BufferSize>
using LoggerAsyncCS = BasicLogger< LogWorkerAsync< BufferSize > >
The async logger, this will create a separate thread that will process the logging messages asynchronously.
using LoggerSimpleMT = BasicLogger< LogWorkerSimple< 512, juce::CriticalSection > >
The default sync logger, this will make message processing happen on the same thread as the logging.
using LoggerAsyncMT = BasicLogger< LogWorkerAsync< 512, juce::CriticalSection > >
The async logger, this will create a separate thread that will process the logging messages asynchronously.
template<int BufferSize>
using LoggerSimpleCSMT = BasicLogger< LogWorkerSimple< BufferSize, juce::CriticalSection > >
The default sync logger, this will make message processing happen on the same thread as the logging.
template<int BufferSize>
using LoggerAsyncCSMT = BasicLogger< LogWorkerAsync< BufferSize, juce::CriticalSection > >
The async logger, this will create a separate thread that will process the logging messages asynchronously.
using RotationPolicy = std::function< bool(const RotationPolicyArgs &rotationArgs)>
The rotation policy.
using RotationStrategy = std::function< juce::File(const LogRotationManager &rotationManager)>
The rotation strategy.
using LogSinkCout = detail::LogSinkStandard< std::cout >
using LogSinkCerr = detail::LogSinkStandard< std::cerr >
using LogSinkClog = detail::LogSinkStandard< std::clog >
Enumerations
enum class RwLockGuardAction { Read , Write }
enum class QualifierRef { None , LValue , RValue }
enum class QualifierCv { None , Const , Volatile , ConstVolatile }
Functions
template<class T , class U , class V >
JAUT_NODISCARD JAUT_API constexpr bool fit (T value, U lower, V upper, FitMode mode=FitMode::Lower) noexcept
Tests whether a given number fits the given bound requirements according to the specified mode.
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API bool operator< (T value, const Numeric< U, Checks... > &numeric) noexcept
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API bool operator> (T value, const Numeric< U, Checks... > &numeric) noexcept
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API bool operator== (T value, const Numeric< U, Checks... > &numeric) noexcept
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API bool operator!= (T value, const Numeric< U, Checks... > &numeric) noexcept
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API bool operator<= (T value, const Numeric< U, Checks... > &numeric) noexcept
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API bool operator>= (T value, const Numeric< U, Checks... > &numeric) noexcept
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API Numeric< U, Checks... > operator+ (T value, const Numeric< U, Checks... > &numeric)
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API Numeric< U, Checks... > operator- (T value, const Numeric< U, Checks... > &numeric)
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API Numeric< U, Checks... > operator* (T value, const Numeric< U, Checks... > &numeric)
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API Numeric< U, Checks... > operator/ (T value, const Numeric< U, Checks... > &numeric)
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>>
JAUT_NODISCARD JAUT_API Numeric< U, Checks... > operator% (T value, const Numeric< U, Checks... > &numeric)
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<allowsBitOperations_v<T, U>>>
JAUT_NODISCARD JAUT_API Numeric< U, Checks... > operator<< (T value, const Numeric< U, Checks... > &numeric)
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<allowsBitOperations_v<T, U>>>
JAUT_NODISCARD JAUT_API Numeric< U, Checks... > operator>> (T value, const Numeric< U, Checks... > &numeric)
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<allowsBitOperations_v<T, U>>>
JAUT_NODISCARD JAUT_API Numeric< U, Checks... > operator& (T value, const Numeric< U, Checks... > &numeric)
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<allowsBitOperations_v<T, U>>>
JAUT_NODISCARD JAUT_API Numeric< U, Checks... > operator| (T value, const Numeric< U, Checks... > &numeric)
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<allowsBitOperations_v<T, U>>>
JAUT_NODISCARD JAUT_API Numeric< U, Checks... > operator^ (T value, const Numeric< U, Checks... > &numeric)
template<class ... Args>
EventHandler (FunctionPointer_t< void, Args... >) -> EventHandler< Args... >
template<class Obj , class ... Args>
JAUT_NODISCARD JAUT_API auto makeHandler (MemberFunctionPointer_t< Obj, void, Args... > function, Obj &owner)
Creates a new EventHandler from a non-static member function.
template<class Obj , class ... Args>
JAUT_NODISCARD JAUT_API auto makeHandler (MemberFunctionPointer_t< Obj, void, Args... > function, Obj *owner)
Creates a new EventHandler from a non-static member function.
template<class Fn >
JAUT_NODISCARD JAUT_API auto makeHandler (Fn &&invocable)
Creates a new EventHandler from a free function, a lambda or a functor object.
template<class Obj , class ... Args>
JAUT_NODISCARD JAUT_API auto makeHandler (juce::String id, MemberFunctionPointer_t< Obj, void, Args... > function, Obj &owner)
Creates a new associative EventHandler from a non-static member function.
template<class Obj , class ... Args>
JAUT_NODISCARD JAUT_API auto makeHandler (juce::String id, MemberFunctionPointer_t< Obj, void, Args... > function, Obj *owner)
Creates a new associative EventHandler from a non-static member function.
template<class Fn , class ... Args>
JAUT_NODISCARD JAUT_API auto makeHandler (juce::String id, Fn &&invocable)
Creates a new associative EventHandler from a free function, a lambda or a functor object.
template<class Handler , class CriticalSection >
JAUT_NODISCARD JAUT_API auto makeHandler (Event< Handler, CriticalSection > &chainedEvent)
Creates a new chained EventHandler from another Event.
template<class ... Args>
JAUT_API constexpr void ignore (Args &&...)
template<class T >
JAUT_NODISCARD juce::String getActualTypeName (JAUT_MUNUSED T *const type)
template<class T >
JAUT_NODISCARD juce::String getActualTypeName ()
template<class T >
JAUT_NODISCARD juce::String getActualTypeName (JAUT_MUNUSED T &type)
template<class U >
NonNull (NonNull< U > &) -> NonNull< U >
template<class U >
NonNull (NonNull< U > &&) -> NonNull< U >
template<class T >
JAUT_NODISCARD JAUT_API auto makeNonNull (T &&obj) noexcept(noexcept(NonNull(std::forward< T >(obj)))) -> NonNull< T >
template<class Derived , class Base >
JAUT_NODISCARD Derived stynamic_cast (Base *const base) noexcept
Tries to downcast a base class to a derived class without the overhead of "dynamic_cast", this should be used when you are 100% certain that a base class pointer will be an instance to a derived class.
template<class Derived , class Base >
JAUT_NODISCARD Derived stynamic_cast (Base &base) noexcept
Tries to downcast a base class to a derived class without the overhead of "dynamic_cast", this should be used when you are 100% certain that a base class pointer will be an instance to a derived class.
template<class Exception >
void throwAssertFalse (const juce::String &message)
Will assert in debug mode before throwing an exception, so as to that it's easier to find the root cause of a problem in your program.
template<class Exception , class Fn >
void throwAssert (bool mustBeTrue, Fn &&errorBuilder)
Will assert in debug mode before throwing an exception when the condition holds true, so as to that it's easier to find the root cause of a problem in your program.
template<class T >
JAUT_NODISCARD juce::String toString (T &)
template<class T >
JAUT_NODISCARD juce::String toString (const T &)
template<class T >
JAUT_NODISCARD juce::String toString ()
template<class T >
JAUT_NODISCARD juce::String toName ()
template<class T >
JAUT_NODISCARD juce::String toName (const T &)
template<class T >
JAUT_NODISCARD JAUT_API juce::String toString (T &object)
template<class T >
JAUT_NODISCARD JAUT_API juce::String toString (const T &object)
template<class T >
JAUT_NODISCARD JAUT_API juce::String toString ()
template<class T >
JAUT_NODISCARD JAUT_API juce::String toName ()
template<class T >
JAUT_NODISCARD JAUT_API juce::String toName (const T &)
JAUT_NODISCARD LookAndFeel & getDefaultLaf () noexcept
JAUT_NODISCARD JAUT_API LogMessage::Field mfield (const juce::String &key, juce::var value)
Creates a logging field which should be added to the logging message.
Variables
template<class T >
JAUT_API constexpr bool isValidNumeric_v = isValidNumeric<T>::value
Checks whether T is a valid type for the jaut::Numeric class.
template<class T , class U >
JAUT_API constexpr bool allowsBitOperations_v = allowsBitOperations<T, U>::value
Checks whether T and U are valid operations for a bit-wise expression.
template<class Fn , class Handler >
JAUT_API constexpr bool isHandlerFreeFunction_v = isHandlerFreeFunction<Fn, Handler>::value
Determines whether a function is a free function pointer complying to the specified jaut::EventHandler type.
template<class T , class Handler >
JAUT_API constexpr bool isHandlerLambdaOrFunctor_v = isHandlerLambdaOrFunctor<T, Handler>::value
Determines whether a type is either a valid lambda-closure or a functor type complying to the specified jaut::EventHandler type.
constexpr unique_construct_t unique_construct
constexpr unique_construct_t shared_construct
template<class T >
struct JAUT_API toTypeArray
Converts any type-list to a jaut::TypeArray.
template<auto FunctionPointer, class = decltype(FunctionPointer)>
class JAUT_API Function
template<class Signature >
struct JAUT_API Overload
Used to disambiguate function pointers that point to functions with one or more overloads.
template<class T >
JAUT_API constexpr bool isPredicate_v = isPredicate<T>::value
Determines whether the passed type is a jaut::PredicateX type.
template<template< class... > class Required, class Tested >
JAUT_API constexpr bool sameTypeIgnoreTemplate_v = sameTypeIgnoreTemplate<Required, Tested>::value
Determines whether TypeToCheck is of same type as TemplatedType.
template<class T >
JAUT_API constexpr bool isTemplated_v = isTemplated<T>::value
Checks whether type T is a templated type or not.
template<class T >
JAUT_API constexpr bool hasArguments_v = hasArguments<T>::value
Checks whether type T's template list is empty or not.
template<class T , class Key >
JAUT_API constexpr bool hasTemplateType_v = hasTemplateType<T, Key>::value
Checks whether a given type-list contains a specific type at least once.
template<class T >
JAUT_API constexpr std::size_t getTypeListLength_v = getTypeListLength<T>::value
Gets the amount of types in a type-list.
template<class T , class Key >
JAUT_API constexpr auto getIndexOf_v = getIndexOf<T, Key>::value
Gets the index of the first matching type in the given type-list.
template<class Left , class Right >
JAUT_API constexpr bool isEqualityComparable_v = isEqualityComparable<Left, Right>::value
Checks whether two types are equality comparable.
template<class T >
JAUT_API constexpr bool qualifiesAsString_v = qualifiesAsString<T>::value
Checks whether type T could qualify as a string type.
template<class T >
JAUT_API constexpr bool isIterator_v = isIterator<T>::value
Typedef Documentation
TrivialHandler
using jaut::TrivialHandler = typedef EventHandler<>
An EventHandler with no arguments.
Use this instead of EventHandler<> to better express your intent.
FunctionPointer_t
template<class Ret , class ... Types> using jaut::FunctionPointer_t = typedef Ret(*)(Types...)
A convenience type-wrapper for function pointers.
Template Parameters
Ret The return type
Types The function arguments
MemberFunctionPointer_t
template<class Obj , class Ret , class ... Types> using jaut::MemberFunctionPointer_t = typedef Ret(Obj::*)(Types...)
A convenience type-wrapper for pointer-to-member functions.
Template Parameters
Obj The object containing the non-static member function
Ret The return type
Types The function arguments
MemberDataPointer_t
template<class Obj , class T > using jaut::MemberDataPointer_t = typedef T Obj::*
A convenience type-wrapper for pointer-to-member objects.
Template Parameters
Obj The object containing the non-static member object
T The object's type
toTypeArray_t
template<class T > using jaut::toTypeArray_t = typedef typename toTypeArray<T>::type
Converts any type-list to a jaut::TypeArray.
Template Parameters
T The type-list to convert
replaceType_t
template<class T , class Key , class Replacement > using jaut::replaceType_t = typedef typename replaceType<T, Key, Replacement>::type
Replaces a specific type from the type-list of a class with another.
This replaces as many as it finds.
If T is a non templated type or contains value parameters, this will give back T.
Template Parameters
T The class with the type-list
Key The type to be replaced
Replacement The new type that will be inserted instead
getTypeAt_t
template<class T , std::size_t I> using jaut::getTypeAt_t = typedef typename getTypeAt<T, I>::type
Gets a type of a type-list at the specified index.
Template Parameters
T The type-list to get the type from
I The index of the type to fetch
removeFrom_t
template<class T , class ... Remove> using jaut::removeFrom_t = typedef typename removeFrom<T, Remove...>::type
Removes a specified type from a type-list if it exists and gets the new version.
Template Parameters
T The type-list to modify
Remove The types to remove
removeIf_t
template<class T , class Predicate > using jaut::removeIf_t = typedef typename removeIf<T, Predicate>::type
Removes all types from the type-list that match the given predicate.
For more information on Predicates, refer to jaut::Predicate.
Template Parameters
T The type-list to modify
Predicate The predicate which must be met
See also
jaut::Predicate
addIfAbsent_t
template<class T , class ... Add> using jaut::addIfAbsent_t = typedef typename addIfAbsent<T, Add...>::type
Adds a type to a type-list if it isn't already contained.
Template Parameters
T The type-list to modify
Add The types to add
TypeLadder_t
template<class ... Cases> using jaut::TypeLadder_t = typedef typename TypeLadder<Cases...>::type
CidnsJuce
using jaut::CidnsJuce = typedef detail::CidNamespaceInternal<Cid::Juce>
The namespace for JUCE colour IDs.
Do not use this for defining new colour IDs.
CidnsJaut
using jaut::CidnsJaut = typedef detail::CidNamespaceInternal<Cid::Jaut>
The namespace for JAUT colour IDs.
Do not use this for defining new colour IDs.
Thickness
template<class T > using jaut::Thickness = typedef Distance<T>
Specifies the thickness of a border or outline.
Margin
template<class T > using jaut::Margin = typedef Distance<T>
Specifies the distance from the outside of a component to the border of its parent.
Padding
template<class T > using jaut::Padding = typedef Distance<T>
Specifies the distance from the inside of a component to all its children.
LoggerSimple
using jaut::LoggerSimple = typedef BasicLogger<LogWorkerSimple<> >
The default sync logger, this will make message processing happen on the same thread as the logging.
This variant will give you the default sync logger with a buffer size of 512 and no lock on the producer site.
LoggerAsync
using jaut::LoggerAsync = typedef BasicLogger<LogWorkerAsync<> >
The async logger, this will create a separate thread that will process the logging messages asynchronously.
This variant will give you the default async logger with a buffer size of 512 and no lock on the producer site.
LoggerSimpleCS
template<int BufferSize> using jaut::LoggerSimpleCS = typedef BasicLogger<LogWorkerSimple<BufferSize> >
The default sync logger, this will make message processing happen on the same thread as the logging.
This variant will give you a sync logger with a custom buffer size and no lock on the producer site.
Template Parameters
BufferSize The size of the log worker message buffer
LoggerAsyncCS
template<int BufferSize> using jaut::LoggerAsyncCS = typedef BasicLogger<LogWorkerAsync<BufferSize> >
The async logger, this will create a separate thread that will process the logging messages asynchronously.
This variant will give you an async logger with a custom buffer size and no lock on the producer site.
Template Parameters
BufferSize The size of the log worker message buffer
LoggerSimpleMT
using jaut::LoggerSimpleMT = typedef BasicLogger<LogWorkerSimple<512, juce::CriticalSection> >
The default sync logger, this will make message processing happen on the same thread as the logging.
This variant will give you a sync logger with a default buffer size of 512 and a lock on the producer site.
LoggerAsyncMT
using jaut::LoggerAsyncMT = typedef BasicLogger<LogWorkerAsync<512, juce::CriticalSection> >
The async logger, this will create a separate thread that will process the logging messages asynchronously.
This variant will give you an async logger with a default buffer size of 512 and a lock on the producer site.
LoggerSimpleCSMT
template<int BufferSize> using jaut::LoggerSimpleCSMT = typedef BasicLogger<LogWorkerSimple<BufferSize, juce::CriticalSection> >
The default sync logger, this will make message processing happen on the same thread as the logging.
This variant will give you a sync logger with a custom buffer size and a lock on the producer site.
Template Parameters
BufferSize The size of the log worker message buffer
LoggerAsyncCSMT
template<int BufferSize> using jaut::LoggerAsyncCSMT = typedef BasicLogger<LogWorkerAsync<BufferSize, juce::CriticalSection> >
The async logger, this will create a separate thread that will process the logging messages asynchronously.
This variant will give you an async logger with a custom buffer size and a lock on the producer site.
Template Parameters
BufferSize The size of the log worker message buffer
RotationPolicy
using jaut::RotationPolicy = typedef std::function<bool(const RotationPolicyArgs &rotationArgs)>
The rotation policy.
The policy will determine whether the log should be rotated when it returns true. Usually you can do that with a lambda, but if you have a more complex policy a functor class is preferable.
Parameters
rotationArgs The data that is needed to calculate whether it should be rotated
Returns
True if the rotation should happen now, false if no rotation is necessary
RotationStrategy
using jaut::RotationStrategy = typedef std::function<juce::File(const LogRotationManager &rotationManager)>
The rotation strategy.
The strategy will determine how log files are rotated and where and under what name they will end up. For simple strategies, a lambda is more than enough but can be extended to a functor class for a more-configurable approach.
If this is used in conjunction with jaut::SinkRotatingFile, you do not need to take care of closing/deleting the main log file.
Parameters
currentLogFile The log rotation manager that this callback is tied to
Returns
The newly rotated archive file
LogSinkCout
using jaut::LogSinkCout = typedef detail::LogSinkStandard<std::cout>
LogSinkCerr
using jaut::LogSinkCerr = typedef detail::LogSinkStandard<std::cerr>
LogSinkClog
using jaut::LogSinkClog = typedef detail::LogSinkStandard<std::clog>
Enumeration Type Documentation
RwLockGuardAction
enum class jaut::RwLockGuardAction strong
Enumerator
Read
Write
QualifierRef
enum class jaut::QualifierRef strong
Enumerator
None
LValue
RValue
QualifierCv
enum class jaut::QualifierCv strong
Enumerator
None
Const
Volatile
ConstVolatile
Function Documentation
fit()
template<class T , class U , class V > JAUT_NODISCARD JAUT_API constexpr bool jaut::fit (T value, U lower, V upper, FitMode mode = FitMode::Lower) constexpr noexcept
Tests whether a given number fits the given bound requirements according to the specified mode.
Template Parameters
T The type to test
U The type of the lower bound
V The type of the upper bound
Parameters
value The number to test
lower The lower bound of the checked range
upper The upper bound of the checked range
Returns
True if the tested value fits inside the range
operator<()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API bool jaut::operator< (T value, const Numeric< U, Checks... > & numeric) noexcept
operator>()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API bool jaut::operator> (T value, const Numeric< U, Checks... > & numeric) noexcept
operator==()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API bool jaut::operator== (T value, const Numeric< U, Checks... > & numeric) noexcept
Referenced by jaut::EventHandler< HandlerArgs >::EventHandler(), jaut::Distance< T >::operator!=(), jaut::EventHandler< HandlerArgs >::operator!=(), and jaut::Size< T >::operator!=().
operator!=()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API bool jaut::operator!= (T value, const Numeric< U, Checks... > & numeric) noexcept
Referenced by jaut::EventHandler< HandlerArgs >::EventHandler().
operator<=()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API bool jaut::operator<= (T value, const Numeric< U, Checks... > & numeric) noexcept
operator>=()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API bool jaut::operator>= (T value, const Numeric< U, Checks... > & numeric) noexcept
operator+()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API Numeric< U, Checks... > jaut::operator+ (T value, const Numeric< U, Checks... > & numeric)
operator-()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API Numeric< U, Checks... > jaut::operator- (T value, const Numeric< U, Checks... > & numeric)
operator*()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API Numeric< U, Checks... > jaut::operator* (T value, const Numeric< U, Checks... > & numeric)
operator/()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API Numeric< U, Checks... > jaut::operator/ (T value, const Numeric< U, Checks... > & numeric)
operator%()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<isValidNumeric_v<T>>> JAUT_NODISCARD JAUT_API Numeric< U, Checks... > jaut::operator% (T value, const Numeric< U, Checks... > & numeric)
operator<<()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<allowsBitOperations_v<T, U>>> JAUT_NODISCARD JAUT_API Numeric< U, Checks... > jaut::operator<< (T value, const Numeric< U, Checks... > & numeric)
operator>>()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<allowsBitOperations_v<T, U>>> JAUT_NODISCARD JAUT_API Numeric< U, Checks... > jaut::operator>> (T value, const Numeric< U, Checks... > & numeric)
operator&()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<allowsBitOperations_v<T, U>>> JAUT_NODISCARD JAUT_API Numeric< U, Checks... > jaut::operator& (T value, const Numeric< U, Checks... > & numeric)
operator|()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<allowsBitOperations_v<T, U>>> JAUT_NODISCARD JAUT_API Numeric< U, Checks... > jaut::operator| (T value, const Numeric< U, Checks... > & numeric)
operator^()
template<class T , class U , NumericCheck... Checks, class = std::enable_if_t<allowsBitOperations_v<T, U>>> JAUT_NODISCARD JAUT_API Numeric< U, Checks... > jaut::operator^ (T value, const Numeric< U, Checks... > & numeric)
EventHandler()
template<class ... Args> jaut::EventHandler (FunctionPointer_t< void, Args... >) -> EventHandler< Args... >
makeHandler() [1/7]
template<class Obj , class ... Args> JAUT_NODISCARD JAUT_API auto jaut::makeHandler (MemberFunctionPointer_t< Obj, void, Args... > function, Obj & owner)
Creates a new EventHandler from a non-static member function.
Template Parameters
Obj The owner type of the member function
Parameters
function The member function to link
owner An instance of the class holding the member function
Returns
The new EventHandler object
makeHandler() [2/7]
template<class Obj , class ... Args> JAUT_NODISCARD JAUT_API auto jaut::makeHandler (MemberFunctionPointer_t< Obj, void, Args... > function, Obj * owner)
Creates a new EventHandler from a non-static member function.
Template Parameters
Obj The owner type of the member function
Args The argument types of the handler
Parameters
function The member function to link
owner An instance of the class holding the member function
Returns
The new EventHandler object
makeHandler() [3/7]
template<class Fn > JAUT_NODISCARD JAUT_API auto jaut::makeHandler (Fn && invocable)
Creates a new EventHandler from a free function, a lambda or a functor object.
Template Parameters
Args The argument types of the handler
Parameters
invocable The invocable to create the handler from
Returns
The new EventHandler object
makeHandler() [4/7]
template<class Obj , class ... Args> JAUT_NODISCARD JAUT_API auto jaut::makeHandler (juce::String id, MemberFunctionPointer_t< Obj, void, Args... > function, Obj & owner)
Creates a new associative EventHandler from a non-static member function.
Template Parameters
Obj The owner type of the member function
Parameters
id The id of the handler
function The member function to link
owner An instance of the class holding the member function
Returns
The new EventHandler object
makeHandler() [5/7]
template<class Obj , class ... Args> JAUT_NODISCARD JAUT_API auto jaut::makeHandler (juce::String id, MemberFunctionPointer_t< Obj, void, Args... > function, Obj * owner)
Creates a new associative EventHandler from a non-static member function.
Template Parameters
Obj The owner type of the member function
Parameters
id The id of the handler
function The member function to link
owner An instance of the class holding the member function
Returns
The new EventHandler object
makeHandler() [6/7]
template<class Fn , class ... Args> JAUT_NODISCARD JAUT_API auto jaut::makeHandler (juce::String id, Fn && invocable)
Creates a new associative EventHandler from a free function, a lambda or a functor object.
Template Parameters
Args The argument types of the handler
Parameters
id The id of the handler
invocable The invocable to create the handler from
Returns
The new EventHandler object
makeHandler() [7/7]
template<class Handler , class CriticalSection > JAUT_NODISCARD JAUT_API auto jaut::makeHandler (Event< Handler, CriticalSection > & chainedEvent)
Creates a new chained EventHandler from another Event.
Template Parameters
Handler The handler of the other event
Parameters
chainedEvent The chained event to create the handler from
Returns
The new EventHandler object
ignore()
template<class ... Args> JAUT_API constexpr void jaut::ignore (Args && ...) constexpr
Referenced by jaut::TypeArray<>::allocate(), jaut::TypeArray<>::construct(), jaut::TypeArray<>::fillArray(), jaut::TypeArray<>::forAll(), jaut::TypeArray<>::forAll(), jaut::TypeArray<>::forEach(), jaut::TypeArray<>::forEach(), jaut::TypeArray<>::iterate(), jaut::TypeArray<>::makeShared(), jaut::TypeArray<>::makeUnique(), and jaut::ILogSink::prepare().
getActualTypeName() [1/3]
template<class T > JAUT_NODISCARD juce::String jaut::getActualTypeName (JAUT_MUNUSED T *const type)
getActualTypeName() [2/3]
template<class T > JAUT_NODISCARD juce::String jaut::getActualTypeName ()
Referenced by jaut::LogMessage::ExceptionSpec::fromException(), getActualTypeName(), and stynamic_cast().
getActualTypeName() [3/3]
template<class T > JAUT_NODISCARD juce::String jaut::getActualTypeName (JAUT_MUNUSED T & type)
References getActualTypeName().
NonNull() [1/2]
template<class U > jaut::NonNull (NonNull< U > &) -> NonNull< U >
NonNull() [2/2]
template<class U > jaut::NonNull (NonNull< U > &&) -> NonNull< U >
makeNonNull()
template<class T > JAUT_NODISCARD JAUT_API auto jaut::makeNonNull (T && obj) -> NonNull<T> noexcept
stynamic_cast() [1/2]
template<class Derived , class Base > JAUT_NODISCARD Derived jaut::stynamic_cast (Base *const base) noexcept
Tries to downcast a base class to a derived class without the overhead of "dynamic_cast", this should be used when you are 100% certain that a base class pointer will be an instance to a derived class.
If this assumption is false, in debug builds will assert.
This makes it possible for making sure a type is of a certain polymorphic type in debug builds, and when it is, remove this check in release builds.
Template Parameters
Derived The type to cast the base type to
Parameters
base The pointer to the base class
Returns
The casted derived object
References dbgassert, and getActualTypeName().
stynamic_cast() [2/2]
template<class Derived , class Base > JAUT_NODISCARD Derived jaut::stynamic_cast (Base & base) noexcept
Tries to downcast a base class to a derived class without the overhead of "dynamic_cast", this should be used when you are 100% certain that a base class pointer will be an instance to a derived class.
If this assumption is false, in debug builds will assert.
This makes it possible for making sure a type is of a certain polymorphic type in debug builds, and when it is, remove this check in release builds.
Template Parameters
Derived The type to cast the base type to
Parameters
base The reference to the base class
Returns
The casted derived object
throwAssertFalse()
template<class Exception > void jaut::throwAssertFalse (const juce::String & message)
Will assert in debug mode before throwing an exception, so as to that it's easier to find the root cause of a problem in your program.
The error will also be printed to the debug console first, to make sure you have a reasonable message to understand the issue at hand.
Template Parameters
Exception The exception class to throw
Parameters
errorBuilder A lambda returning a string, this is so that the string has not to be created if no error occurs
References dbgassertfalse.
throwAssert()
template<class Exception , class Fn > void jaut::throwAssert (bool mustBeTrue, Fn && errorBuilder)
Will assert in debug mode before throwing an exception when the condition holds true, so as to that it's easier to find the root cause of a problem in your program.
The error will also be printed to the debug console first, to make sure you have a reasonable message to understand the issue at hand.
The message will be passed by lambda, so that when the evaluation works in favour of not throwing, the string does not have to be unnecessarily created.
Template Parameters
Exception The exception class to throw
Parameters
mustBeTrue The condition that must be true to avoid an assert throw
errorBuilder A lambda returning a string
toString() [1/6]
template<class T > JAUT_NODISCARD juce::String jaut::toString (T & object)
References toString().
Referenced by jaut::Stringable< juce::NamedValueSet >::toString(), and jaut::Stringable< juce::SystemStats >::toString().
toString() [2/6]
template<class T > JAUT_NODISCARD juce::String jaut::toString (const T & object)
References toString().
toString() [3/6]
template<class T > JAUT_NODISCARD juce::String jaut::toString ()
References toString().
Referenced by jaut::AbstractLogger::LogBuilder::operator<<(), toString(), jaut::Stringable< juce::ArgumentList >::toString(), jaut::Stringable< juce::Array< T, CS, N > >::toString(), jaut::Stringable< juce::Atomic< T > >::toString(), jaut::Stringable< juce::HashMap< T, U, Ect... > >::toString(), jaut::Stringable< juce::NamedValueSet >::toString(), jaut::Stringable< juce::NormalisableRange< T > >::toString(), jaut::Stringable< juce::var >::toString(), jaut::Stringable< LogMessage >::toString(), jaut::Stringable< LogMessage::Field >::toString(), jaut::Stringable< std::array< T, N > >::toString(), toString(), jaut::Stringable< T >::toString(), jaut::Stringable< juce::DynamicObject >::toString(), jaut::Stringable< juce::PropertySet >::toString(), and toString().
toName() [1/4]
template<class T > JAUT_NODISCARD juce::String jaut::toName ()
References jaut::Stringable< T >::name().
toName() [2/4]
template<class T > JAUT_NODISCARD juce::String jaut::toName (const T &)
toString() [4/6]
template<class T > JAUT_NODISCARD JAUT_API juce::String jaut::toString (T & object)
References toString().
Referenced by jaut::Stringable< juce::NamedValueSet >::toString(), and jaut::Stringable< juce::SystemStats >::toString().
toString() [5/6]
template<class T > JAUT_NODISCARD JAUT_API juce::String jaut::toString (const T & object)
References toString().
toString() [6/6]
template<class T > JAUT_NODISCARD JAUT_API juce::String jaut::toString ()
References toString().
Referenced by jaut::AbstractLogger::LogBuilder::operator<<(), toString(), jaut::Stringable< juce::ArgumentList >::toString(), jaut::Stringable< juce::Array< T, CS, N > >::toString(), jaut::Stringable< juce::Atomic< T > >::toString(), jaut::Stringable< juce::HashMap< T, U, Ect... > >::toString(), jaut::Stringable< juce::NamedValueSet >::toString(), jaut::Stringable< juce::NormalisableRange< T > >::toString(), jaut::Stringable< juce::var >::toString(), jaut::Stringable< LogMessage >::toString(), jaut::Stringable< LogMessage::Field >::toString(), jaut::Stringable< std::array< T, N > >::toString(), toString(), jaut::Stringable< T >::toString(), jaut::Stringable< juce::DynamicObject >::toString(), jaut::Stringable< juce::PropertySet >::toString(), and toString().
toName() [3/4]
template<class T > JAUT_NODISCARD JAUT_API juce::String jaut::toName ()
References jaut::Stringable< T >::name().
toName() [4/4]
template<class T > JAUT_NODISCARD JAUT_API juce::String jaut::toName (const T &)
getDefaultLaf()
JAUT_NODISCARD LookAndFeel & jaut::getDefaultLaf () noexcept
mfield()
JAUT_NODISCARD JAUT_API LogMessage::Field jaut::mfield (const juce::String & key, juce::var value)
Creates a logging field which should be added to the logging message.
Parameters
key The field key
value The field value
Returns
The new field
Variable Documentation
isValidNumeric_v
template<class T > JAUT_API constexpr bool jaut::isValidNumeric_v = isValidNumeric<T>::value constexpr
Checks whether T is a valid type for the jaut::Numeric class.
Valid types are any integral (non-boolean) and floating point types.
Returns
True if the type is valid, false otherwise
allowsBitOperations_v
template<class T , class U > JAUT_API constexpr bool jaut::allowsBitOperations_v = allowsBitOperations<T, U>::value constexpr
Checks whether T and U are valid operations for a bit-wise expression.
This will be true if none of both types is a floating point number.
Returns
True if the type is valid, false otherwise
isHandlerFreeFunction_v
template<class Fn , class Handler > JAUT_API constexpr bool jaut::isHandlerFreeFunction_v = isHandlerFreeFunction<Fn, Handler>::value constexpr
Determines whether a function is a free function pointer complying to the specified jaut::EventHandler type.
Template Parameters
Fn The function pointer type
Handler The corresponding jaut::EventHandler type
isHandlerLambdaOrFunctor_v
template<class T , class Handler > JAUT_API constexpr bool jaut::isHandlerLambdaOrFunctor_v = isHandlerLambdaOrFunctor<T, Handler>::value constexpr
Determines whether a type is either a valid lambda-closure or a functor type complying to the specified jaut::EventHandler type.
Template Parameters
T The functor or closure type
Handler The corresponding jaut::EventHandler type
unique_construct
constexpr unique_construct_t jaut::unique_construct constexpr
shared_construct
constexpr unique_construct_t jaut::shared_construct constexpr
toTypeArray
template<class T > struct JAUT_API jaut::toTypeArray
Converts any type-list to a jaut::TypeArray.
Template Parameters
T The type-list to convert
Function
template<auto FunctionPointer, class = decltype(FunctionPointer)> class JAUT_API jaut::Function
Overload
template<class Signature > struct JAUT_API jaut::Overload
Used to disambiguate function pointers that point to functions with one or more overloads.
Template Parameters
Signature The function signature (e.g. "void(int, double)")
isPredicate_v
template<class T > JAUT_API constexpr bool jaut::isPredicate_v = isPredicate<T>::value constexpr
Determines whether the passed type is a jaut::PredicateX type.
Template Parameters
T The type to check
sameTypeIgnoreTemplate_v
template<template< class... > class Required, class Tested > JAUT_API constexpr bool jaut::sameTypeIgnoreTemplate_v = sameTypeIgnoreTemplate<Required, Tested>::value constexpr
Determines whether TypeToCheck is of same type as TemplatedType.
The difference to the std version is that this one only checks for the type class regardless its templates.
Note that this does not work with mixed type/value parameters, such as for std::array this will evaluate to false. But you can add your own specialisation for these cases:
namespace jaut
{
    template<class T, class U, auto N, auto N2>
    struct sameTypeIgnoreTemplate<std::array<T, N>, std::array<U, N2>> : public std::true_type {};
}
Template Parameters
Required The required type
Tested The tested type
isTemplated_v
template<class T > JAUT_API constexpr bool jaut::isTemplated_v = isTemplated<T>::value constexpr
Checks whether type T is a templated type or not.
Note that this does not work with mixed type/value parameters, such as for std::array this will evaluate to false. But you can add your own specialisation for these cases:
namespace jaut
{
    template<class T, auto N>
    struct isTemplated<std::array<T, N>> : public std::true_type {};
}
Template Parameters
T The type to check
hasArguments_v
template<class T > JAUT_API constexpr bool jaut::hasArguments_v = hasArguments<T>::value constexpr
Checks whether type T's template list is empty or not.
Note that this does not work with mixed type/value parameters, such as for std::array this will evaluate to false. But you can add your own specialisation for these cases:
namespace jaut
{
    template<class T, auto N>
    struct hasArguments<std::array<T, N>> : std::true_type {};
}
Template Parameters
T The type to check
hasTemplateType_v
template<class T , class Key > JAUT_API constexpr bool jaut::hasTemplateType_v = hasTemplateType<T, Key>::value constexpr
Checks whether a given type-list contains a specific type at least once.
Template Parameters
T The type-list to check
Key The type to check for
getTypeListLength_v
template<class T > JAUT_API constexpr std::size_t jaut::getTypeListLength_v = getTypeListLength<T>::value constexpr
Gets the amount of types in a type-list.
Template Parameters
T The type-list to check
getIndexOf_v
template<class T , class Key > JAUT_API constexpr auto jaut::getIndexOf_v = getIndexOf<T, Key>::value constexpr
Gets the index of the first matching type in the given type-list.
Template Parameters
T The type-list to search
Key The type to find the index for
isEqualityComparable_v
template<class Left , class Right > JAUT_API constexpr bool jaut::isEqualityComparable_v = isEqualityComparable<Left, Right>::value constexpr
Checks whether two types are equality comparable.
Template Parameters
Left The left type of the equality operator
Right The right type of the equality operator
qualifiesAsString_v
template<class T > JAUT_API constexpr bool jaut::qualifiesAsString_v = qualifiesAsString<T>::value constexpr
Checks whether type T could qualify as a string type.
Note that this does not check whether the type actually is a string type, just that it could be one.
Template Parameters
T The type to check
isIterator_v
template<class T > JAUT_API constexpr bool jaut::isIterator_v = isIterator<T>::value constexpr