JAUT: jaut::ISerialisableAudioProcessor Struct Reference
jaut::ISerialisableAudioProcessor Struct Reference abstract
A simple interface class for sub-audio processors for your own processor implementation.
#include <jaut_ISerialisableAudioProcessor.h>
Public Member Functions
virtual ~ISerialisableAudioProcessor ()=default
virtual void process (juce::AudioBuffer< float > &buffer, juce::MidiBuffer &midiBuffer)=0
Processes the current block with single-precisions and gives back the modified data.
virtual void process (juce::AudioBuffer< double > &buffer, juce::MidiBuffer &midiBuffer)
Processes the current block with double-precisions and gives back the modified data.
virtual JAUT_NODISCARD juce::String getName () const =0
Gets the name of this processor object.
virtual JAUT_NODISCARD std::unique_ptr< juce::Component > createComponent () const
If this processor creates a component, it can be embedded by overriding this method.
virtual void prepare (ProcessSpec specs)=0
This is called before any playback is about to happen.
virtual void release ()=0
This is called after any playback has happened.
virtual void reset ()
It is unclear when this is called by the host or if it is called at all.
virtual void readData (juce::ValueTree state)=0
Reads data from the loaded state and applies it to the audio processor.
virtual void writeData (juce::ValueTree state)=0
Write data to the state object which was read from the audio processor.
Detailed Description
A simple interface class for sub-audio processors for your own processor implementation.
In contrast to juce::AudioProcessor, this version of audio processor does not need the huge interface AudioProcessor provides. Instead, this class tries to reduce its interface to just the most important needs such as processing and, of course, serialising state.
If you want to use a AudioProcessor-based processor, you can proxy it with SerialisableJuceProcessorProxy.
See also
SerialisableJuceProcessorProxy
Constructor & Destructor Documentation
~ISerialisableAudioProcessor()
virtual jaut::ISerialisableAudioProcessor::~ISerialisableAudioProcessor () virtual default
Member Function Documentation
process() [1/2]
virtual void jaut::ISerialisableAudioProcessor::process (juce::AudioBuffer< float > & buffer, juce::MidiBuffer & midiBuffer) pure virtual
Processes the current block with single-precisions and gives back the modified data.
Parameters
buffer The buffer containing the sample data
midiBuffer The buffer containing the midi messages
Implemented in jaut::AudioProcessorRack, jaut::SerialisableJuceProcessorProxy< InternalAudioProcessor >, and jaut::AudioProcessorSet< Processors >.
process() [2/2]
virtual void jaut::ISerialisableAudioProcessor::process (juce::AudioBuffer< double > & buffer, juce::MidiBuffer & midiBuffer) virtual
Processes the current block with double-precisions and gives back the modified data.
Parameters
buffer The buffer containing the sample data
midiBuffer The buffer containing the midi messages
Reimplemented in jaut::AudioProcessorRack, jaut::SerialisableJuceProcessorProxy< InternalAudioProcessor >, and jaut::AudioProcessorSet< Processors >.
getName()
virtual JAUT_NODISCARD juce::String jaut::ISerialisableAudioProcessor::getName () const pure virtual
Gets the name of this processor object.
Returns
The processor name
Implemented in jaut::AudioProcessorRack, jaut::AudioProcessorSet< Processors >, and jaut::SerialisableJuceProcessorProxy< InternalAudioProcessor >.
createComponent()
virtual JAUT_NODISCARD std::unique_ptr< juce::Component > jaut::ISerialisableAudioProcessor::createComponent () const virtual
If this processor creates a component, it can be embedded by overriding this method.
Returns
The new component
Reimplemented in jaut::SerialisableJuceProcessorProxy< InternalAudioProcessor >.
Referenced by jaut::SerialisableJuceProcessorProxy< InternalAudioProcessor >::createComponent().
prepare()
virtual void jaut::ISerialisableAudioProcessor::prepare (ProcessSpec specs) pure virtual
This is called before any playback is about to happen.
Mainly used for preparing resources like allocating buffers and/or storing temporary values that are needed inside the processing routine.
Parameters
specs A struct containing basic records about playback
Implemented in jaut::AudioProcessorRack, jaut::AudioProcessorSet< Processors >, and jaut::SerialisableJuceProcessorProxy< InternalAudioProcessor >.
release()
virtual void jaut::ISerialisableAudioProcessor::release () pure virtual
This is called after any playback has happened.
Here the resources previously used can be cleaned up and deallocated, made ready for the next playback.
Implemented in jaut::AudioProcessorRack, jaut::AudioProcessorSet< Processors >, and jaut::SerialisableJuceProcessorProxy< InternalAudioProcessor >.
reset()
virtual void jaut::ISerialisableAudioProcessor::reset () virtual
It is unclear when this is called by the host or if it is called at all.
See juce::AudioProcessor::reset() for a better explanation on how this method behaves.
Reimplemented in jaut::AudioProcessorRack, jaut::AudioProcessorSet< Processors >, and jaut::SerialisableJuceProcessorProxy< InternalAudioProcessor >.
readData()
virtual void jaut::ISerialisableAudioProcessor::readData (juce::ValueTree state) pure virtual
Reads data from the loaded state and applies it to the audio processor.
Parameters
state The state object to read from
Implemented in jaut::AudioProcessorRack, jaut::AudioProcessorSet< Processors >, and jaut::SerialisableJuceProcessorProxy< InternalAudioProcessor >.
Referenced by jaut::AudioProcessorSet< Processors >::readData().
writeData()
virtual void jaut::ISerialisableAudioProcessor::writeData (juce::ValueTree state) pure virtual
Write data to the state object which was read from the audio processor.
Parameters
state The state object to write to
Implemented in jaut::AudioProcessorRack, jaut::AudioProcessorSet< Processors >, and jaut::SerialisableJuceProcessorProxy< InternalAudioProcessor >.
Referenced by jaut::AudioProcessorSet< Processors >::writeData().
The documentation for this struct was generated from the following file:
/github/workspace/modules/jaut_audio/processor/jaut_ISerialisableAudioProcessor.h